const express = require("express");
const router = express.Router();
const auth = require("../middleware/auth");
const proOnly = require("../middleware/proOnly");
const Task = require("../models/Task");

// Create custom task
router.post("/", auth, proOnly, async (req, res) => {
  try {
    const task = await Task.create({
      user: req.userId,
      plant: req.body.plantId,
      title: req.body.title,
      description: req.body.description || "",
      dueDate: req.body.dueDate,
      priority: req.body.priority || 1,
      type: "custom",
      autoGenerated: false,
    });
    res.json(task);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// List today's tasks
router.get("/today", auth, async (req, res) => {
  try {
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const end = new Date();
    end.setHours(23, 59, 59, 999);

    const tasks = await Task.find({ user: req.userId, dueDate: { $gte: start, $lte: end } })
      .populate("plant", "name strain")
      .sort({ priority: -1 });

    res.json(tasks);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// All upcoming tasks
router.get("/upcoming", auth, async (req, res) => {
  try {
    const tasks = await Task.find({ user: req.userId, completed: false, dueDate: { $gte: new Date() } })
      .populate("plant", "name strain")
      .sort({ dueDate: 1 });

    res.json(tasks);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Complete task
router.post("/:id/complete", auth, proOnly, async (req, res) => {
  try {
    const task = await Task.findOneAndUpdate({ _id: req.params.id, user: req.userId }, { completed: true }, { new: true });
    res.json(task);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
