const express = require("express");
const router = express.Router();
const auth = require("../middleware/auth");
const proOnly = require("../middleware/proOnly");
const Template = require("../models/Template");
const Plant = require("../models/Plant");
const Task = require("../models/Task");

// CREATE TEMPLATE (creator)
router.post("/", auth, proOnly, async (req, res) => {
  try {
    const { title, description, strain, growMedium, difficulty, durationDays, price, tags, steps } = req.body;

    const template = await Template.create({
      creator: req.userId,
      title,
      description,
      strain,
      growMedium,
      difficulty,
      durationDays,
      price: price || 0,
      tags: tags || [],
      steps: steps || [],
    });

    res.json(template);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// LIST TEMPLATES (marketplace)
router.get("/", auth, async (req, res) => {
  try {
    const { tag, difficulty, maxPrice } = req.query;
    const query = { isPublished: true };
    if (tag) query.tags = tag;
    if (difficulty) query.difficulty = difficulty;
    if (maxPrice) query.price = { $lte: Number(maxPrice) };

    const templates = await Template.find(query)
      .populate("creator", "username avatar")
      .sort({ createdAt: -1 });

    res.json(templates);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// LIST MY TEMPLATES (as creator)
router.get("/mine/created", auth, async (req, res) => {
  try {
    const templates = await Template.find({ creator: req.userId }).sort({ createdAt: -1 });
    res.json(templates);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// GET SINGLE TEMPLATE
router.get("/:id", auth, async (req, res) => {
  try {
    const template = await Template.findById(req.params.id).populate("creator", "username avatar");
    if (!template) return res.status(404).json({ message: "Not found" });
    res.json(template);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// APPLY TEMPLATE TO PLANT AND GENERATE TASKS
router.post("/:id/apply/:plantId", auth, proOnly, async (req, res) => {
  try {
    const template = await Template.findById(req.params.id);
    const plant = await Plant.findOne({ _id: req.params.plantId, user: req.userId });

    if (!template || !plant) {
      return res.status(404).json({ message: "Not found" });
    }

    if (!plant.templates.map((t) => t.toString()).includes(template._id.toString())) {
      plant.templates.push(template._id);
      await plant.save();
    }

    const startDate = plant.startDate ? new Date(plant.startDate) : new Date();

    await Promise.all(
      (template.steps || []).map((step) => {
        const dueDate = new Date(startDate);
        dueDate.setDate(dueDate.getDate() + (step.day || 0));
        return Task.create({
          user: req.userId,
          plant: plant._id,
          template: template._id,
          title: step.label,
          description: step.details || "",
          type: "template",
          dueDate,
          priority: 1,
          autoGenerated: true,
        });
      })
    );

    res.json({ success: true, plant });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
