export const ROLE_ALIASES: Record<string, "OWNER" | "MANAGER" | "STAFF" | "VIEWER"> =
  Object.freeze({
    TECH: "STAFF"
  });

export const CAPABILITY_ALIASES: Record<string, string> = Object.freeze({
  "FACILITY.SETTINGS.EDIT": "FACILITY_SETTINGS_EDIT",
  FACILITY_SETTINGS_EDIT: "FACILITY_SETTINGS_EDIT",
  DIAGNOSE_AI: "DIAGNOSE_AI",
  DIAGNOSE_ADVANCED: "DIAGNOSE_ADVANCED",
  DIAGNOSE_EXPORT: "DIAGNOSE_EXPORT",
  COURSES_ANALYTICS: "COURSES_ANALYTICS",
  COURSES_CREATE: "COURSES_CREATE",
  COURSES_AFFILIATE: "COURSES_AFFILIATE",
  GROWLOGS_EXPORT: "GROWLOGS_EXPORT",
  GROWLOGS_MULTI: "GROWLOGS_MULTI",
  GROWLOGS_BATCH: "GROWLOGS_BATCH",
  GROWLOGS_COMPLIANCE: "GROWLOGS_COMPLIANCE",
  TEAM_INVITE: "TEAM_INVITE",
  TEAM_UPDATE_ROLE: "TEAM_UPDATE_ROLE",

  GROWS_VIEW: "GROWS_READ",
  GROWS_EDIT: "GROWS_WRITE",
  TASKS_VIEW: "TASKS_READ",
  TASKS_EDIT: "TASKS_WRITE",
  PLANTS_VIEW: "PLANTS_READ",
  PLANTS_EDIT: "PLANTS_WRITE",
  TEAM_MANAGE: "TEAM_INVITE",
  TEAM_VIEW: "TEAM_VIEW"
});
