// Canonical mapping of plans/modes to capabilities
// Update as new plans or capabilities are added
import { CAPABILITIES } from "./keys.js";

export const PLANS = {
  personal: [
    CAPABILITIES.VIEW_DASHBOARD,
    CAPABILITIES.VIEW_PROFILE,
    CAPABILITIES.EDIT_PROFILE,
    CAPABILITIES.VIEW_COURSES,
    CAPABILITIES.ENROLL_COURSE,
    CAPABILITIES.VIEW_FORUM,
    CAPABILITIES.POST_FORUM
  ],
  commercial: [
    CAPABILITIES.VIEW_DASHBOARD,
    CAPABILITIES.VIEW_PROFILE,
    CAPABILITIES.EDIT_PROFILE,
    CAPABILITIES.VIEW_COURSES,
    CAPABILITIES.ENROLL_COURSE,
    CAPABILITIES.MANAGE_ENROLLMENTS,
    CAPABILITIES.VIEW_FORUM,
    CAPABILITIES.POST_FORUM,
    CAPABILITIES.MANAGE_USERS,
    CAPABILITIES.VIEW_PAYMENTS
  ],
  facility: [
    CAPABILITIES.VIEW_DASHBOARD,
    CAPABILITIES.VIEW_PROFILE,
    CAPABILITIES.EDIT_PROFILE,
    CAPABILITIES.VIEW_COURSES,
    CAPABILITIES.ENROLL_COURSE,
    CAPABILITIES.MANAGE_ENROLLMENTS,
    CAPABILITIES.VIEW_FORUM,
    CAPABILITIES.POST_FORUM,
    CAPABILITIES.MANAGE_USERS,
    CAPABILITIES.MANAGE_FACILITY,
    CAPABILITIES.VIEW_PAYMENTS,
    CAPABILITIES.MANAGE_PAYMENTS
  ]
};

export default PLANS;
