const mongoose = require("mongoose");

const TaskSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    plant: { type: mongoose.Schema.Types.ObjectId, ref: "Plant" },
    template: { type: mongoose.Schema.Types.ObjectId, ref: "Template" },
    title: String,
    description: String,
    dueDate: Date,
    priority: { type: Number, default: 1 },
    type: { type: String, enum: ["template", "custom"], default: "template" },
    completed: { type: Boolean, default: false },
    autoGenerated: { type: Boolean, default: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Task", TaskSchema);
