export interface GrowPathMethod {
  id: string;
  title: string;
  appliesTo: string[];
  summary: string;
  primaryWorkflow: string[];
  requiredInputs: string[];
  requiredOutputs: string[];
  warnings: string[];
  relatedTools: string[];
  sourcePolicy: string;
  documentPath: string;
}

function method(
  id: string,
  title: string,
  appliesTo: string[],
  document: string,
  workflow: string[],
  inputs: string[],
  outputs: string[],
  warnings: string[],
  tools: string[]
): GrowPathMethod {
  return {
    id,
    title,
    appliesTo,
    summary: workflow.join(" → "),
    primaryWorkflow: workflow,
    requiredInputs: inputs,
    requiredOutputs: outputs,
    warnings,
    relatedTools: tools,
    sourcePolicy:
      "Apply source-reliability-registry by use case; distinguish records, calculations, inference and claims.",
    documentPath: `docs/knowledge/methods/${document}`
  };
}

export const methodRegistry: GrowPathMethod[] = [
  method(
    "integration-workflow",
    "Integration Workflow",
    ["integration", "telemetry", "sensor", "controller"],
    "integration-workflow-method.md",
    ["connect", "test", "discover", "map", "confirm", "auto-build"],
    ["provider credentials", "target workspace", "reviewed mappings"],
    [
      "spaces",
      "devices",
      "normalized streams",
      "raw metric evidence",
      "tool input context",
      "field-use declarations",
      "draft alerts",
      "dashboard definitions"
    ],
    ["Read-only first; never invent metrics, units, mappings, or control access."],
    ["data-integrations", "facility-integrations", "telemetry"]
  ),
  method(
    "plant-diagnosis-etgu",
    "Plant Diagnosis — ETGU",
    ["diagnosis", "ipm"],
    "plant-diagnosis-etgu-method.md",
    ["pattern", "medium", "environment", "numbers", "likely causes"],
    [
      "selected grow/plant",
      "crop/stage and scout zone",
      "written symptom pattern",
      "symptom progression",
      "plants checked and affected",
      "distribution within and across plants",
      "underside and magnification findings",
      "dated trap count with location/exposure context",
      "media with analysis status",
      "explicitly selected existing grow media with grow/plant/log provenance",
      "up to 12 role-diverse review photos with zoomed-out context and focused detail",
      "one optional private source video up to 9 minutes 59 seconds with up to 12 timestamped candidate still frames spanning the timeline",
      "grow history",
      "environment with explicit units",
      "pH/EC"
    ],
    [
      "evidence",
      "counterEvidence",
      "likelyIssues",
      "nextChecks",
      "discriminating follow-up question",
      "follow-up analysis that preserves the original structured evidence",
      "image analysis performed status",
      "photo count and provider/model execution evidence",
      "distinct overall confidence, ranked-candidate confidence, health status, and action urgency",
      "IPM readiness and ranked working hypotheses",
      "IPM supporting evidence, counter-evidence, and competing candidates",
      "safe treatment categories without pesticide products or dosing",
      "normalized GrowPath/GPT agreement state",
      "explicit IPM AI-credit cost and charged/refunded result",
      "user likely/uncertain/rejected decision with timestamp",
      "grow-optional draft crop identity from uploaded media",
      "defensible common, genus, or family-level candidate retained when exact species is unresolved",
      "crop-identification photo count, provider/model, quality, visible traits, evidence IDs, and limitations preserved and visible in the saved result",
      "explicitly confirmed crop identity persisted to the selected grow/plant"
    ],
    [
      "Do not declare a nutrient deficiency from appearance alone.",
      "Do not scrape Facebook or other social groups, treat post engagement as diagnostic truth, or copy a community image without platform authorization and image-level creator rights.",
      "Use rights-reviewed community cases only as QA/evaluation leads or photo-quality negative controls; require confirmed outcomes and Tier A cross-checks before they influence diagnosis or IPM logic.",
      "Do not silently prefill diagnosis stage or symptom location, and do not present ranked-candidate confidence as overall confidence.",
      "Do not imply attached photos were visually analyzed by a text-only provider.",
      "Preserve optional source videos as private non-AI evidence and analyze only up to 12 extracted timestamped still frames; never claim direct video or motion analysis.",
      "Do not send existing private grow media to diagnosis or IPM until the user explicitly selects each photo and its grow/plant/log provenance is preserved.",
      "Do not drop attached photo evidence or prior crop-identity provenance during follow-up analysis, treat a supplied crop name as explicit confirmation, or coerce blank measurements to zero.",
      "A structured GPT IPM second opinion does not independently inspect photo or video pixels.",
      "Do not label a combined billable scout-and-GPT action as a free calculator or hide its AI-credit cost until after the run.",
      "Do not count empty AI-prefill keys as filled fields or display raw empty arrays as scout evidence.",
      "Do not derive scout or trap counts from photos, and do not count unknown placeholder phrases as completed IPM fields.",
      "Do not strand a newly selected diagnosis or IPM upload as non-AI-usable after explicitly disclosing and receiving current-workflow AI approval.",
      "Do not invent scout defaults, trap context, organism identity, pesticide products, or rates.",
      "Do not require a grow for crop identification or infer a cultivar from cannabis flower appearance.",
      "Do not replace a defensible broader crop candidate with a confirmation placeholder merely because exact species remains unresolved.",
      "Do not discard server-attested crop-identification vision provenance and relabel an analyzed result as text-only or unanalyzed.",
      "Collect identification photos before the AI action and reserve user confirmation for the explicit result action.",
      "Recognizing cannabis from deliberately submitted crop-identification evidence must not unlock or advertise unrelated cannabis-only workflows."
    ],
    ["plant-diagnosis", "ipm-scout", "ask-ai"]
  ),
  method(
    "pheno-hunting",
    "Pheno Hunting",
    ["genetics", "selection"],
    "pheno-hunting-method.md",
    ["early growth", "flower", "final product", "clone/TC", "decision"],
    ["plant history", "stress", "sensory", "yield", "propagation"],
    ["category decisions", "reasoning", "retest plan"],
    ["A composite score cannot replace final-product and role-specific decisions."],
    ["pheno-hunt", "pheno-matrix", "genetics-inventory"]
  ),
  method(
    "stress-testing",
    "Stress Testing and Recovery",
    ["stress", "selection"],
    "stress-testing-method.md",
    ["incident", "response", "recovery", "lasting impact"],
    ["stress history", "before/after evidence", "timing"],
    ["recovery record", "keeper impact", "tasks"],
    ["Do not invent resilience scores."],
    ["stress-test", "pheno-hunt"]
  ),
  method(
    "crop-steering",
    "Crop Steering",
    ["irrigation", "environment"],
    "crop-steering-method.md",
    ["intent", "measured pressure", "response", "stop/continue"],
    ["medium", "dryback", "EC/pH", "DLI/VPD", "response"],
    ["optional techniques", "prerequisites", "stop conditions"],
    ["Do not escalate pressure with missing data or unresolved stress."],
    ["crop-steering-project", "crop-steering-entry", "ph-ec-check"]
  ),
  method(
    "soil-nutrients",
    "Soil and Nutrients",
    ["soil", "water", "nutrients"],
    "soil-and-nutrient-method.md",
    [
      "open the unified mix-builder chooser",
      "select exactly one soil or nutrient builder",
      "verified inputs",
      "chemistry or structure",
      "release",
      "application"
    ],
    [
      "mix goal",
      "verified labels",
      "batch and water context",
      "stage",
      "lab or measured evidence when available",
      "history"
    ],
    [
      "label/elemental math or soil structure plan",
      "release timeline",
      "source confidence and uncertainty",
      "antagonisms",
      "commercial batch yield, packaging, cost completeness and inventory review",
      "tasks"
    ],
    [
      "Compost, biology, mineralization and long-term availability remain uncertain without testing.",
      "Official labels support guaranteed analysis and use rates, not superiority, uptake or crop response.",
      "Do not coerce missing batch quantity, analysis, cost, shrinkage, margin, lot or inventory values to zero.",
      "Calculate blended label analysis only from complete values expressed in compatible quantity units; inventory review never decrements stock."
    ],
    [
      "npk",
      "soil-builder",
      "ingredient-library",
      "nutrient-chemistry",
      "nutrient-source-comparison",
      "dry-amendment-mix",
      "topdress-plan",
      "ph-ec-check",
      "watering",
      "feeding-schedule"
    ]
  ),
  method(
    "clone-rooting",
    "Clone Rooting",
    ["propagation"],
    "clone-rooting-method.md",
    [
      "select owned cannabis/hemp grow",
      "count batch",
      "record direct root evidence",
      "record measured context",
      "review bottlenecks and missing evidence",
      "schedule recount",
      "record outcome"
    ],
    [
      "days since cut",
      "total/rooted/failed counts",
      "direct root evidence",
      "optional callus/wilt counts",
      "timestamp and measurement source",
      "humidity, air/root-zone temperature, PPFD and photoperiod when measured",
      "mother health, sanitation, medium, stem and leaf observations",
      "photo analysis provenance"
    ],
    [
      "evidence status",
      "validated batch counts and percentages",
      "measured environment snapshot",
      "structured bottlenecks and counter-limits",
      "missing information",
      "source and method IDs",
      "recount/photo/environment/outcome tasks"
    ],
    [
      "Require an owned cannabis/hemp grow at the API boundary.",
      "Do not use elapsed days, top growth, callus, or tug resistance as proof of hidden roots.",
      "Do not silently default counts, environmental measurements, donor health, sanitation, or media observations.",
      "Present published environmental ranges as cultivar- and study-specific context, never universal targets.",
      "Attached media is not analyzed unless provider execution evidence confirms pixel inspection."
    ],
    ["clone-rooting"]
  ),
  method(
    "tissue-culture",
    "Tissue Culture",
    ["lab", "propagation", "genetics"],
    "tissue-culture-method.md",
    [
      "select owned cannabis/hemp grow",
      "identify batch, workflow lane and stage",
      "record timestamped direct vessel counts",
      "link lineage, SOP, media, sterilization and custody",
      "review visible patterns without naming microorganisms",
      "review quality controls and release blockers",
      "compare protocol, acclimation, storage and recovery outcomes",
      "schedule owner-timed follow-up"
    ],
    [
      "project and batch identifiers",
      "mother-bank, production, cold-storage or cryopreservation lane",
      "stage and direct-inspection status",
      "timestamp, observation source and total/condition vessel counts",
      "lineage, vessel/rack/shelf, SOP/media/sterilization lots and custody",
      "quality-control reports and disposition",
      "measured environment, protocol cohort, acclimation, cost and storage evidence",
      "photo analysis provenance"
    ],
    [
      "assessment, lane and stage",
      "validated counts and percentages",
      "structured visible failure modes and limits",
      "traceability and release blockers",
      "quality, protocol, acclimation, cost, storage and recovery records",
      "source and method IDs",
      "evidence and owner-timed tasks"
    ],
    [
      "Require an owned cannabis/hemp grow at the API boundary.",
      "Do not silently default counts, identifiers, lots, measurements, costs or transfer timing.",
      "Visible patterns and photos cannot identify microorganisms, prove pathogen freedom or replace laboratory evidence.",
      "Do not automatically release material; surface blockers for owner review.",
      "Keep ordinary cold storage separate from validated cryopreservation.",
      "Published protocol values are study- and genotype-specific context, not universal targets."
    ],
    ["tissue-culture"]
  ),
  method(
    "run-comparison",
    "Run Comparison and Grow History",
    ["run comparison", "grow history", "analytics"],
    "run-comparison-method.md",
    [
      "select two to five owned grows",
      "choose reference, objective and equivalent scope",
      "inventory saved evidence",
      "compare recorded values",
      "separate differences from associated drivers",
      "review missing data and alternatives",
      "save report and optional next-run tasks"
    ],
    [
      "owned grow IDs",
      "reference grow",
      "comparison objective",
      "equivalent stage or whole-run scope",
      "saved logs, tasks, ToolRuns, diagnoses, telemetry and outcomes"
    ],
    [
      "evidence inventory by grow",
      "normalized snapshots",
      "recorded differences",
      "associated-driver hypotheses with alternatives",
      "missing information",
      "confidence and limitations",
      "method and source IDs",
      "owner-reviewed follow-up tasks"
    ],
    [
      "Do not use demo runs or silently convert missing values to zero.",
      "Do not rank an overall best run with hidden weights.",
      "Do not compare unlike stages without an explicit limitation.",
      "Do not claim causation from an observational run comparison.",
      "Exclude synthetic QA evidence from ordinary production conclusions unless it is explicitly selected and labeled.",
      "The deterministic comparison uses no AI credit; optional AI explanation must preserve the same evidence limits."
    ],
    ["run-comparison"]
  ),
  method(
    "harvest-dry-cure",
    "Harvest, Dry and Cure",
    ["harvest", "post-harvest"],
    "harvest-dry-cure-method.md",
    [
      "readiness evidence",
      "decision",
      "measured dry/cure",
      "outcome",
      "photo-review provenance and AI-credit outcome"
    ],
    [
      "three macro bud-site photos plus one wider context photo",
      "up to 12 role-diverse photos when additional representative bud sites are needed",
      "one optional private source video up to 9 minutes 59 seconds with up to 12 timestamped candidate still frames spanning the timeline",
      "maturity",
      "telemetry",
      "sensory",
      "simultaneous measured room temperature and RH",
      "optional coldest material or container surface temperature",
      "equilibrated jar or bag RH",
      "measurement time and source",
      "days in the current stage",
      "explicit light exposure condition",
      "airflow and material density"
    ],
    [
      "window",
      "missing media",
      "risk",
      "tasks",
      "air dew point and explicitly labeled air spread",
      "surface-to-dew-point margin only when a surface temperature was measured",
      "evidence used, missing information, and limitations",
      "stage timing that distinguishes a 24-hour recheck from completion",
      "10-14 day controlled-dry planning context and 5-7 day fast-dry quality warning",
      "review ID, evidence IDs, provider/model and image detail, set-level quality checks, per-image findings, visible traits, limitations, photo count, and credit status"
    ],
    [
      "Never estimate sensor values from images.",
      "Never default missing dry/cure temperature, RH, airflow, or density to a plausible-looking value; incomplete measurements produce an insufficient-evidence result.",
      "Never call air temperature minus dew point a surface condensation margin. Calculate a surface margin only from an entered coldest-surface measurement.",
      "Never label mold risk as low or ruled out from one room reading, a photo, or the absence of visible growth.",
      "Keep drying and curing material protected from light; record dark, brief work light, continuous indirect light, direct light, or unknown without guessing from a photo.",
      "Treat a 24-hour task as a recheck, never completion. Show 10-14 days only as a controlled-drying planning window, 5-7 days as a possible fast/hot/low-humidity quality concern, and longer than 14 days as possible but not recommended as routine; elapsed time alone never completes the stage.",
      "Require cannabis/hemp grow context at the Dry / Cure Guard API boundary before saving a ToolRun.",
      "Never fill trichome percentages after upload failure, unavailable analysis, incomplete provider output, or unusable media; show actionable retake guidance.",
      "Block provider use and spend no AI credit until three sharp macro bud-site samples plus one wider context photo are uploaded and approved for this workflow.",
      "Reject obviously tiny or invalid files before upload, but use actionable retake guidance rather than pretending metadata alone can detect blur, glare, lighting, or missing sample roles.",
      "Use provider high-detail image review, but never claim digital zoom restored pixels hidden by blur, compression, or clipped glare; exclude obscured heads and report each image's usable region or exclusion reason.",
      "Preserve an optional source video shorter than 10 minutes as non-AI evidence and analyze only up to 12 timestamped candidate still frames spanning its timeline. Each frame counts toward the 12-photo ceiling and must pass the same macro, role, focus, lighting, and glare checks. Exclude glare-obscured apparent cloudiness; classify clear, cloudy, or amber only from separate sharp, glare-free visible gland heads under neutral light.",
      "Reserve one disclosed AI credit only after evidence ownership is verified, refund provider failures, and preserve the charge/refund result in the review.",
      "Reject crop-neutral accounts and unrelated horticulture grows before loading harvest evidence or reserving an AI credit.",
      "Never silently coerce missing trichome observations to zero or score a distribution that does not total about 100%.",
      "Keep the shared harvest-readiness route discoverable in cannabis-aware Personal Tools and contextual cannabis grow surfaces, including untagged legacy cannabis grows and grows with attached cannabis-only workflow evidence."
    ],
    ["harvest-readiness", "dry-cure-guard"]
  ),
  method(
    "video-sharing-workflow",
    "Video Sharing Workflow",
    ["video", "discovery", "following", "media"],
    "video-sharing-workflow-method.md",
    [
      "upload or link",
      "reserve and verify private storage",
      "review rights and accessibility",
      "save once",
      "publish with visibility",
      "discover or follow",
      "reuse by reference"
    ],
    [
      "active Personal, Commercial, or Facility workspace",
      "video source",
      "title and description",
      "creator rights confirmation",
      "availability and accessibility review",
      "explicit visibility",
      "cannabis/hemp classification",
      "authoritative storage size for GrowPath uploads"
    ],
    [
      "workspace-owned reusable video record",
      "truthful workspace storage usage and limit",
      "verified private object and authorized short-lived playback",
      "public or follower-scoped Discover result",
      "creator follow action from video detail",
      "stable course and content references",
      "reference-safe detach and deletion status",
      "cannabis-aware discovery filtering"
    ],
    [
      "Never limit video upload or sharing only to accounts labeled as creators.",
      "Never let Facility Staff remove another member's draft or any published Facility video.",
      "Never expose private, unlisted, course-only, or Facility-internal videos in public Discover.",
      "Never treat a client-provided flag as proof that the viewer follows a video owner.",
      "Never duplicate an upload merely to attach one reusable video to a course.",
      "Never delete a library video while a course or supported record still references it.",
      "Never claim storage was released until the storage service confirms physical deletion.",
      "Never persist object-storage credentials or expiring signed upload or playback URLs in video, course, or lesson records.",
      "Never show cannabis/hemp-specific video discovery to unrelated horticulture viewers.",
      "Never treat video popularity, follows, or engagement as scientific verification or AI-training permission."
    ],
    ["videos", "discover", "course-builder", "profiles", "following-feed"]
  ),
  method(
    "course-media-workflow",
    "Course Media Workflow",
    ["course", "lesson", "education", "media", "payment", "refund"],
    "course-media-workflow-method.md",
    [
      "choose source",
      "normalize provider",
      "review rights and availability",
      "record accessibility fallback",
      "publish",
      "privacy-aware playback"
    ],
    [
      "GrowPath upload or video-page URL",
      "creator rights confirmation",
      "timestamped availability check",
      "captions or transcript status",
      "learner-visible text summary",
      "signature-verified paid checkout webhook",
      "active learner enrollment",
      "recorded refund or payment-support state"
    ],
    [
      "normalized provider metadata",
      "canonical URL and provider ID",
      "Vimeo unlisted privacy hash when present",
      "approved embed capability or link-only fallback",
      "learner-visible availability and accessibility status",
      "external provider link",
      "authorized short-lived playback for protected GrowPath library videos",
      "GrowPath-only explicit completion state",
      "owner-only draft preview and published-only public detail access",
      "learner preview without authoring controls",
      "signed-out published catalog without owned-course or authoring controls",
      "one provider-aware media contract shared by initial course creation and later lesson editing",
      "owner-controlled publish and private-draft unpublish",
      "single page heading, ordered level-two builder steps, one shared back action, and checked pricing or access controls",
      "paid discovery metadata without protected lesson, assessment, document, or media content",
      "webhook-confirmed paid enrollment and idempotent course counters",
      "buyer-visible payment, refund, and GrowPath support status",
      "refund-adjusted and dispute-held creator earning",
      "creator payout eligibility limited to available unpaid earnings"
    ],
    [
      "Never accept or execute author-supplied iframe, script, object, embed, video, or HTML markup.",
      "Never imply GrowPath owns, hosts, continuously monitors, or verifies watch analytics for third-party media.",
      "Never publish video without rights confirmation, a timestamped availability check, accessibility status, text summary, and external-link fallback.",
      "Never drop a Vimeo unlisted privacy hash while normalizing its canonical or player URL.",
      "Never persist object-storage credentials or expiring signed playback URLs in a course or lesson.",
      "Never expose unpublished course or lesson content to anonymous users or unrelated accounts, including through a direct record ID.",
      "Never request owned courses or expose authoring, invite, analytics, publish, unpublish, enrollment, purchase, or progress controls before authentication.",
      "Never expose submit, approve, or reject course actions unless a real moderated-review backend workflow and role policy are implemented end to end.",
      "Never expose duplicate course-authoring back actions, multiple page-level headings, unchecked pricing or access choices, or raw stored values as course labels.",
      "Never expose paid lesson text, media, documents, assessments, protected playback, or completion controls before active enrollment.",
      "Never treat checkout creation, a success redirect, direct enrollment, or lesson completion as proof of paid access.",
      "Never increment paid enrollment, revenue, or creator earnings more than once when Stripe retries a webhook.",
      "Never show refund or payment-issue forms without a recorded paid purchase, or label GrowPath support intake as a bank, card-network, or Stripe dispute.",
      "Never include held or refunded course earnings in creator payout eligibility.",
      "Provider playback never completes a GrowPath lesson automatically."
    ],
    [
      "course-builder",
      "course-player",
      "commercial-courses",
      "facility-training",
      "course-payments"
    ]
  ),
  method(
    "commercial-workflow",
    "Commercial Workflow",
    ["commercial"],
    "commercial-workflow-method.md",
    ["formula", "batch", "trial", "outcome", "product"],
    ["commercial records", "verified claims"],
    [
      "linked workflow",
      "limitations",
      "tasks",
      "single-heading campaign authoring with named stateful controls",
      "campaign draft review that distinguishes planned publish status from current state and uses user-facing filters",
      "inactive Commercial tab screens detached from web layout and focus order",
      "compact Commercial navigation with the active secondary workspace and a complete More destination",
      "compact shared-page content and campaign rails retained in non-overlapping document flow",
      "one level-one Product Lines heading with level-two workflow sections and level-three saved-line headings",
      "one level-one Soil & Nutrient Batch Planner heading with level-two workflow sections and level-three saved-batch headings",
      "one level-one Product Trials heading with level-two workflow sections and level-three saved-trial headings",
      "one level-one Product Trial Evidence Runs heading with distinct level-two workflow sections and level-three saved-run headings",
      "one level-one Commercial Inventory Support heading with level-two workflow sections and level-three saved-record headings",
      "capability-gated Commercial inventory creation exposed as a named actionable control",
      "readable owner-scoped Product Trial record pickers with an explicit advanced ID fallback",
      "readable owner-scoped Product Batch record pickers with an explicit advanced ID fallback",
      "readable owner-scoped Product Trial Evidence Run record pickers and named share status choices with an explicit advanced ID fallback",
      "named Inventory Support item types and readable Product or Evidence Run pickers with an explicit advanced fallback",
      "forum alerts",
      "accessible inline Forum reply expansion and text reply composition on canonical post previews",
      "canonical Forum Directory group discovery and accessible group creation",
      "moderation audit",
      "server-enforced audited Forum moderation with feed-projection removal, reversible soft removal, and locked-reply blocking",
      "owner-scoped event analytics",
      "one level-one Commercial Analytics heading with level-two metrics, breakdown, and guidance sections",
      "bounded Personal home campaign density that preserves the grow workspace",
      "owner-scoped production batches linked to ToolRuns and Commercial tasks",
      "published-course discovery limited to published storefronts and explicit public fields",
      "slug-gated public storefront preview actions with truthful setup guidance",
      "explicit dispensary discovery by state or user-authorized distance with published linked inventory and external-site or in-store-pickup handoff",
      "signed-out course discovery limited to published learner-facing catalog fields",
      "signed-out Forum boundary with sign-in and registration actions instead of a protected-feed error",
      "direct draft-course detail limited to the authenticated author or platform administrator",
      "explicit eligible workspace preference preserved across plan-backed modes",
      "post-login workspace choice for every multi-workspace identity",
      "direct-entry and hard-reload support for workspace choice and switching",
      "workspace preference reapplied before restricted-route access decisions",
      "workspace selection and routing use the same effective paid-plan capabilities",
      "one 30-day trial per paid plan for Pro, Commercial, and Facility, with legacy trial use mapped to Pro and a second price-labeled confirmation before immediate Stripe billing",
      "visible Checkout success or cancellation feedback with an account refresh after success",
      "review-only SOP/checklist recommendations with starter version, rationale, missing information, and separately confirmed grow-task conversion",
      "clear not-configured guidance for unavailable third-party integrations",
      "connection-derived read-only EventSub status and checked Commercial Live visibility controls",
      "readable calendar selection with direct year, month, day, and optional time controls"
    ],
    [
      "Never cross workspace scope or invent product claims.",
      "Never expose campaign types, placements, filters, or publish actions as generic unnamed controls.",
      "Never describe a blocked or unpublished campaign draft as currently active or expose raw campaign type values as filter labels.",
      "Never leave focusable controls from an inactive Commercial tab in the web keyboard order.",
      "Never let compact campaign rails shrink, cover, intercept, or displace Commercial workspace controls.",
      "Never expose a duplicate navigator title or a flat generic-text outline on Product Lines.",
      "Never expose a duplicate navigator title or a flat generic-text outline on the Soil & Nutrient Batch Planner.",
      "Never expose a duplicate navigator title or a flat generic-text outline on Product Trials.",
      "Never expose a duplicate navigator title or reuse one generic section label for different Product Trial Evidence Run jobs.",
      "Never expose a duplicate navigator title or a flat generic-text outline on Commercial Inventory Support.",
      "Never expose an authorized Commercial inventory write entry point as visually clickable generic text.",
      "Never require an ordinary Commercial user to find or paste database IDs to link a Product Trial.",
      "Never require copied database IDs as the primary way to connect a Product Batch to saved Commercial records.",
      "Never require copied database IDs or raw public-share status codes as the primary Product Trial Evidence Run creation workflow.",
      "Never make opaque record IDs or undocumented type values the default Commercial inventory setup workflow.",
      "Never require a page transition merely to read or write an ordinary Forum text reply from a canonical post preview.",
      "Never strand Forum group creation in a legacy compatibility screen or hide public-versus-private discoverability.",
      "Never leave hidden or soft-removed Forum content in shared feeds, accept replies on locked threads, hard-delete moderation evidence, or perform a moderator action without a case and platform audit event.",
      "Never count repeated Forum reports from the same account toward an automatic hold threshold.",
      "Never hide a Commercial workspace at compact widths without a visible replacement path from More.",
      "Never expose Commercial Analytics metric, breakdown, or guidance sections as additional level-one page headings.",
      "A batch calculation may report inventory shortages but cannot decrement stock, assign lots, publish claims or authorize release.",
      "Never expose drafts, owner/account IDs, arbitrary authoring fields, or private records through public commercial-course discovery.",
      "Never route a public storefront preview through an invented or placeholder slug.",
      "Never include dispensaries in default horticulture discovery or offer GrowPath checkout, payment, delivery, shipping, or reservation for a dispensary item.",
      "Never invent dispensary availability or imply pickup completion; use published linked inventory and a dispensary-provided website or pickup instructions.",
      "Never expose course authoring controls or request owned-course records for an anonymous visitor.",
      "Never call the protected Forum feed for a signed-out visitor, invent a public thread list, or present an authorization failure as an empty Forum.",
      "Never treat knowledge of a draft course ID as permission to read, enroll, check out, discuss, or review it.",
      "Never honor deterministic test identity headers as production authentication.",
      "Never silently replace an explicitly selected eligible workspace with the account's primary billing mode.",
      "Never repeat a trial for the same paid plan or consume another paid plan's trial when one plan's trial is used.",
      "Never open an immediately billed Stripe checkout on the first action after the selected plan's trial has been used.",
      "Never present a Commercial AI procedure draft as an approved Facility SOP, invent its setpoints, chemical rates, or legal requirements, or save it without separate confirmation.",
      "Never inject a Facility plan, rating scale, approved limit, deviation process, label, or Facility role into a Personal or Commercial procedure recommendation unless selected records explicitly provide it.",
      "Never pass reserved public route words or malformed record IDs into database ID queries.",
      "Never allow an author to type an integration into a connected state or expose Commercial Live visibility as unselected raw values.",
      "Never expose raw integration transport codes as workflow content or claim an integration is connected without verified configuration state.",
      "Never require an ordinary Commercial user to type an ISO date or date-time string."
    ],
    ["commercial-batch-planner", "soil-nutrient-batch", "products", "trials", "forum-qna"]
  ),
  method(
    "facility-workflow",
    "Facility Workflow",
    ["facility"],
    "facility-workflow-method.md",
    ["facility", "room/zone", "assignment", "SOP/task", "audit"],
    ["facility scope", "roles", "rooms", "telemetry"],
    [
      "scoped actions",
      "audit links",
      "forum tasks and alerts",
      "moderation audit",
      "Facility-scoped audited Forum moderation with feed-projection removal, reversible soft removal, and locked-reply blocking",
      "read-only integration state",
      "reviewed device mapping",
      "record-backed facility analytics",
      "read-after-write Facility invitation session handoff",
      "Facility-subscription-backed member role capabilities",
      "selected-Facility AI balance, reservation, refund, and weekly usage ledger",
      "legacy missing-balance materialization from an effective owner Facility entitlement",
      "individual-versus-Facility workspace choice after sign-in",
      "direct-entry and hard-reload support for workspace choice and switching",
      "cross-platform confirmed Facility member removal with preserved history",
      "title-based public outreach destination selection with advanced reference fallback",
      "read-after-write reconciled facility task queues",
      "stable accessible Facility task queue links",
      "credential-autofill-safe AI and parental-control inputs",
      "record-backed report counts with explicit untracked compliance evidence",
      "export readiness separated by open, resolved, and cancelled deviation status",
      "human-readable audit summaries with full-record drill-in",
      "readable audit-detail evidence context before immutable raw payloads",
      "readable selected-Facility context without database identifiers",
      "record-backed non-submitting Facility AI readiness presets",
      "notification-backed Facility alerts with supported source and task actions",
      "named Facility task assignments, rooms, and record summaries",
      "readable Facility inventory details with confirmed mistaken-record removal",
      "collision-resistant Facility deviation references with controlled write failures",
      "template-backed or owner-entered SOP checklists",
      "owner-reviewed setpoint-free standard SOP starters",
      "Personal and Commercial AI reuse limited to review-only starter recommendations",
      "Facility-scoped SOP document attachments that supplement an executable checklist",
      "version-preserving SOP revisions and non-destructive retirement",
      "Facility-scoped SOP create, revise, and retire audit events with readable title and version context",
      "human-readable two-run SOP comparison selection",
      "review-complete and mutation-locked SOP evidence runs",
      "readable SOP evidence summaries and step differences",
      "separate seed-readiness and post-seed QA evidence",
      "readable calendar selection with direct year, month, day, and optional time controls"
    ],
    [
      "A selected facility and authorization are required.",
      "Facility AI must use the selected authorized Facility subscription balance for display, reservation, refund, and usage history; never fall back to a member's individual balance.",
      "Only a missing legacy Facility balance with an effective active or trialing owner Facility entitlement may be materialized; existing canceled or delinquent Facility subscription state remains authoritative.",
      "A confirmed Facility invitation must refresh canonical membership and enter the selected Facility without replacing the human's primary account.",
      "Never replace an individual account with Facility membership or bypass the post-login choice when both workspaces are eligible.",
      "Never rely on native-only Alert callbacks for web member-removal confirmation or remove the last owner.",
      "Never leave hidden or soft-removed Facility Forum content in eligible feeds, accept replies on locked threads, hard-delete moderation evidence, or change Facility-only visibility during moderation.",
      "Never count repeated Facility Forum reports from the same account toward an automatic hold threshold.",
      "Local previews require explicit preview intent; bare routes preserve real authenticated Facility sessions.",
      "Never hide a confirmed Facility task write behind a cached or stale queue response.",
      "Never make Facility outreach operators type raw course, live-event, or Forum identifiers when readable public records are available.",
      "Never make Facility task operators work from raw database fields, user IDs, room IDs, or JSON records.",
      "Never expose raw Facility inventory envelopes or internal identifiers as the primary item detail, or leave authorized operators unable to remove a mistaken record.",
      "Never expose raw source-object IDs in Facility task queue summaries or route a task row anywhere except its selected task detail.",
      "Never invite saved account credentials into an AI prompt or parental-control PIN field.",
      "Never use an internal Facility identifier as the visible workspace name, operational context label, or downloaded evidence filename.",
      "Never ignore a selected Facility AI preset, auto-submit its request, fabricate missing inspection evidence, or claim legal compliance.",
      "Never show assign, snooze, or AI controls for a notification-backed alert without a server-backed action and its exact source context.",
      "Never show a raw account identifier as the assignee on a Facility alert card.",
      "Never route a notification-backed task alert to a detail record that may have been deleted; open the current task collection instead.",
      "Never leave a zero-grow Facility room at a backend-facing dead end or silently attach a room-scoped grow setup to every Facility room.",
      "Never convert unavailable Facility compliance evidence to a zero or expose raw JSON, entity IDs, or identifier arrays in primary audit lists and summaries.",
      "Never make a Facility operator interpret raw audit JSON before showing the readable action, summary, time, and available actor context.",
      "Never treat a resolved or cancelled Facility deviation as an open cleanup blocker.",
      "Never allow a Facility deviation reference collision or persistence error to terminate the shared API service.",
      "Never create an empty SOP run or require a user to type internal run IDs for comparison.",
      "Never auto-install a standard SOP starter as Facility policy or present it as legal compliance, treatment direction, release criteria, or facility approval.",
      "Never let a Personal or Commercial SOP recommendation imply Facility approval, assignment, uploads, versioning, run evidence, retirement, or audit status.",
      "Never let the shared starter baseline inject a Facility plan, rating scale, approved limit, deviation process, label, or Facility role into a non-Facility recommendation.",
      "Never allow an uploaded SOP document to replace the executable checklist, cross Facility boundaries, or be attached without owner/manager review.",
      "Never overwrite or hard-delete the prior SOP version when a Facility procedure is revised or retired.",
      "Never hide SOP retirement from an authorized owner or manager, label it as deletion, or retire an SOP without naming it and confirming that new runs stop while historical evidence remains.",
      "Never create, revise, or retire a Facility SOP without appending a Facility-scoped lifecycle audit event that can be understood without raw identifiers.",
      "Never complete an SOP run with unreviewed steps, mutate completed evidence, or expose raw run JSON as the primary interface.",
      "Never require an ordinary Facility operator to type an ISO date or date-time string.",
      "Synthetic QA approval never authorizes production records, operational setpoints, publication, or external source rights."
    ],
    [
      "facility-rooms",
      "facility-grows",
      "facility-tasks",
      "facility-inventory",
      "forum-qna"
    ]
  )
];

export function getMethod(id: string) {
  return methodRegistry.find((entry) => entry.id === id);
}

export function methodsForTool(toolKey: string) {
  return methodRegistry.filter((entry) => entry.relatedTools.includes(toolKey));
}
