export interface GrowPathMethod {
  id: string;
  title: string;
  appliesTo: string[];
  summary: string;
  primaryWorkflow: string[];
  requiredInputs: string[];
  requiredOutputs: string[];
  warnings: string[];
  relatedTools: string[];
  sourcePolicy: string;
  documentPath: string;
}

function method(
  id: string,
  title: string,
  appliesTo: string[],
  document: string,
  workflow: string[],
  inputs: string[],
  outputs: string[],
  warnings: string[],
  tools: string[]
): GrowPathMethod {
  return {
    id,
    title,
    appliesTo,
    summary: workflow.join(" -> "),
    primaryWorkflow: workflow,
    requiredInputs: inputs,
    requiredOutputs: outputs,
    warnings,
    relatedTools: tools,
    sourcePolicy:
      "Apply source-reliability-registry by use case; distinguish records, calculations, inference and claims.",
    documentPath: `docs/knowledge/methods/${document}`
  };
}

export const methodRegistry: GrowPathMethod[] = [
  method(
    "integration-workflow",
    "Integration Workflow",
    ["integration", "telemetry", "sensor", "controller"],
    "integration-workflow-method.md",
    ["connect", "test", "discover", "map", "confirm", "auto-build"],
    ["provider credentials", "target workspace", "reviewed mappings"],
    [
      "spaces",
      "devices",
      "normalized streams",
      "raw metric evidence",
      "tool input context",
      "field-use declarations",
      "draft alerts",
      "dashboard definitions"
    ],
    ["Read-only first; never invent metrics, units, mappings, or control access."],
    ["data-integrations", "facility-integrations", "telemetry"]
  ),
  method(
    "plant-diagnosis-etgu",
    "Plant Diagnosis - ETGU",
    ["diagnosis", "ipm", "plant_identification", "field_observation"],
    "plant-diagnosis-etgu-method.md",
    ["pattern", "medium", "environment", "numbers", "likely causes"],
    [
      "selected grow/plant",
      "crop/stage and scout zone",
      "written symptom pattern",
      "symptom progression",
      "plants checked and affected",
      "distribution within and across plants",
      "underside and magnification findings",
      "separate direct organism, disease-sign, damage-pattern, and hypothesis evidence",
      "sentence-level observation and uncertainty scope so speculative comparisons remain hypotheses",
      "affirmed, negated, uncertain, and instructional assertion status for each evidence clause",
      "server-attested media observations, with any diagnostic view role bound to that view's exact finding, quality, and lighting",
      "AI-prefilled field provenance and explicit user-reviewed fields",
      "dated trap count with location/exposure context",
      "media with analysis status",
      "explicitly selected existing grow media with grow/plant/log provenance",
      "exact retained Saved Diagnosis photo IDs explicitly selected for a new authorized re-run without silently selecting an active grow",
      "up to 12 role-diverse review photos with zoomed-out context and focused detail",
      "device-prepared oversized photos with final MIME type and byte size plus terminal upload status",
      "protected original evidence scoped to the active personal, Commercial, or Facility workspace, with a stable retry key and a separate public derivative only after explicit Nature publication",
      "one optional private source video up to 9 minutes 59 seconds with up to 12 timestamped candidate still frames spanning the timeline",
      "structured crop-identification morphology and optional private place/context",
      "optional separately authorized exact device location stored privately with the saved Plant ID ToolRun without requiring a Field Study",
      "explicit user-entered crop-identification context preserved separately from AI visible-trait prefill",
      "whole-plant, leaf, stem/node, flower, fruit/seed, and habitat evidence when available",
      "optional Field Study with owner, editor, verifier, and viewer roles",
      "explicitly selected saved Crop Identification ToolRun and its owned evidence references when linking an existing result to an editable Field Study",
      "editable Field Study, public study visibility, qualifying evidence, explicit observation publication state, public location privacy, and separately captured device coordinates for map readiness",
      "viewer cannabis/hemp grow-interest or content controls for cannabis/hemp pin delivery",
      "at least one owned photo or extracted still with a safe metadata-stripped public derivative before a map pin is delivered",
      "jurisdiction and authoritative source URL before invasive status is called verified",
      "grow history",
      "environment with explicit units",
      "pH/EC"
    ],
    [
      "evidence",
      "counterEvidence",
      "likelyIssues",
      "nextChecks",
      "discriminating follow-up question",
      "follow-up analysis that preserves the original structured evidence",
      "image analysis performed status",
      "photo count and provider/model execution evidence",
      "original-resolution images plus source-bound enlarged diagnostic crops that never count as independent evidence",
      "shared evidence review panel with pixel-analysis status, counter-evidence, missing checks, and re-run guidance",
      "Saved Diagnosis evidence retry that preserves the immutable historical result, revalidates every exact durable AI-approved Diagnosis photo, and starts no analysis or credit use until the user submits",
      "Saved IPM evidence retry that preserves the immutable historical result, revalidates the complete exact durable AI-approved IPM photo/video/frame set, and starts no prefill, second opinion, or credit use until the user submits",
      "distinct overall confidence, ranked-candidate confidence, health status, and action urgency",
      "unusable diagnosis media normalized to an inconclusive low-confidence result with exact retake requests and no image-derived treatment actions",
      "visual-only Diagnosis crop identity capped at medium confidence with exact species broadened to a user-confirmable crop or genus-level draft",
      "IPM readiness and ranked working hypotheses",
      "IPM supporting evidence, counter-evidence, and competing candidates",
      "IPM independent evidence-channel count and confidence ceiling",
      "unresolved white-mark differential with powdery mildew, thrips, mites, residue, mineral deposits, glare, physical damage, and senescence",
      "severity kept not assessed until count, distribution, or progression evidence supports impact assessment",
      "authorized immutable ToolRun follow-up beside the original result with exact evidence, provider, pixel-inspection status, limitations, and one-credit disclosure",
      "server-attested dedicated IPM snapshot and secure-follow-up capability, with structured follow-up confidence and severity capped to saved evidence",
      "cannabis-gated male, female, intersex, or unclear follow-up based on visible reproductive structures rather than stems or stipules",
      "safe treatment categories without pesticide products or dosing",
      "normalized GrowPath/GPT agreement state",
      "one fingerprinted IPM evidence envelope with both answers, deterministic field-level disagreements, combined requested follow-ups, and an explicit unverified billing state until a ledger receipt exists",
      "explicit IPM AI-credit cost and charged/refunded result",
      "user likely/uncertain/rejected decision with timestamp",
      "grow-optional draft crop identity from uploaded media",
      "standalone private Plant ID location that can be added, updated, or removed without creating a Field Study observation or publishing to Nature",
      "deliberately opted-in direct Plant ID publication to a privacy-safe approximate Discovery Nature photo pin without requiring the user to name or configure a Field Study",
      "crop-identification prefill limited to image-visible traits while preserving explicit user context",
      "separate manual-input provenance for explicit identity, morphology, habitat, region, date, setting, and sensory context",
      "exact AI analysis receipt bound to the normalized result digest, evidence fingerprint, policy version, user, and workspace",
      "Plant ID evidence and protected uploads bound to one canonical Personal, Commercial, or Facility workspace, with exact recorded evidence IDs recovered through an authorized scoped lookup",
      "saved Plant ID retry offered only after the complete exact evidence set is revalidated as durable Crop Identification media with every photo AI-approved and every extracted frame linked to its private source video",
      "server-only Plant ID video-frame extraction for a protected private source video, with no client thumbnail generation or frame upload, persisted processing, completed, partial, or failed state, and exact ordered versioned generated-frame recovery before AI submission",
      "defensible common, genus, or family-level candidate retained when exact species is unresolved",
      "crop-identification photo count, provider/model, quality, visible traits, evidence IDs, and limitations preserved and visible in the saved result",
      "crop-identification retake-required state for dark, backlit, harsh-flash, deep-shadow, glare, clipped-highlight, or color-cast evidence that hides diagnostic characters",
      "crop-identification use of sharp illuminated nighttime photos or extracted video frames when diagnostic morphology remains visible, without letting one unusable frame invalidate other compatible usable views",
      "low-confidence candidate-only crop, family, or genus retained when artificial lighting limits exact certainty but readable diagnostic morphology remains, with AI identity prefill and confirmation still blocked",
      "limited-light crop or genus candidate retained only when its own evidence contains a taxon-discriminating character combination, with Cannabis requiring visible reproductive structure plus pistil, resin, or trichome support",
      "low overall and candidate confidence with AI identity fields withheld whenever crop-identification image quality is limited or unusable",
      "provider crop-identification quality and confidence preserved as ceilings that the calculator and saved ToolRun may retain or downgrade but never upgrade",
      "explicit low-confidence disagreement when unchanged evidence produces a conflicting identity or unsupported quality upgrade",
      "ranked crop-identification candidates with evidence, counter-evidence, missing evidence, and next photos/questions",
      "broad group, likely family, possible genera, and species only when supported",
      "role-diverse character-and-value evidence plus affirmative lookalike separation before any exact-species confidence",
      "common and nursery names separated from scientific names, with invalid scientific-name phrases withheld and genus-level drafts retained when supported",
      "low overall and candidate confidence plus a prominent identity-not-verified warning when proposed identity fields conflict or contain an unusable scientific name",
      "user correction that preserves the rejected AI draft, presents the corrected common identity first, leaves unknown exact species unverified, and requests discriminating replacement photos",
      "explicit external-source verification status and empty source records when no database was queried",
      "Facility-scoped Plant ID credits, current-member access, saved runs, logs, and tasks kept outside Personal scope",
      "authenticated Commercial Plant ID ToolRuns kept outside Personal Saved Runs, with unsupported Commercial journal and task actions failing explicitly",
      "user confirmed, uncertain, or rejected identification decision with timestamp",
      "explicitly confirmed crop identity persisted to the selected grow/plant",
      "Field Study observation kept as an AI candidate until separately confirmed or reviewed",
      "existing saved Crop Identification result linked as one private Field Study draft without rerunning AI, re-uploading owned evidence, or changing public state",
      "later user-authorized device coordinates copied into an existing linked private Field Study observation only through a separate audience-aware Field Study action without creating a duplicate",
      "nested identity, evidence, location, publication, sensitivity, cannabis-context, and public-note data preserved across review and sharing updates",
      "legacy saved image-analysis evidence IDs retained as candidate photo references and revalidated for ownership and a safe derivative at publication",
      "visible map-readiness status for editable study, public study visibility, evidence, explicit observation publication, public location privacy, and separately captured coordinates",
      "public observation projection that excludes private coordinates and owner-only provenance",
      "distinct identification verification, plant-health assessment, and jurisdiction-specific invasive status",
      "interactive clustered globe synchronized with a keyboard-accessible observation list",
      "signed-out photo-ready non-cannabis observations with optional-auth cannabis/hemp policy enrichment",
      "cannabis/hemp pins gated by deliberate publication and public context plus viewer grow-interest or content controls"
    ],
    [
      "Do not declare a nutrient deficiency from appearance alone.",
      "Do not scrape Facebook or other social groups, treat post engagement as diagnostic truth, or copy a community image without platform authorization and image-level creator rights.",
      "Use rights-reviewed community cases only as QA/evaluation leads or photo-quality negative controls; require confirmed outcomes and Tier A cross-checks before they influence diagnosis or IPM logic.",
      "Do not silently prefill diagnosis stage or symptom location, and do not present ranked-candidate confidence as overall confidence.",
      "Do not retain high confidence, urgent status, treatment actions, completed tasks, or issue-detected automation from diagnosis media the provider marked unusable, and do not replace explicit user crop context with a conflicting visual suggestion.",
      "Do not promote a visual-only Diagnosis crop suggestion to high-confidence identity, exact species, or cultivar, even when a separate visible issue candidate has higher confidence.",
      "Do not imply attached photos were visually analyzed by a text-only provider.",
      "Do not replace or downscale an original AI-inspection image; enlarged diagnostic crops supplement the original and remain bound to it rather than counting as another photo, sample, site, view role, or observation.",
      "Preserve optional source videos as private non-AI evidence and analyze only up to 12 extracted timestamped still frames; never claim direct video or motion analysis.",
      "Do not run client thumbnail extraction for Plant ID, enable Plant ID while server frame extraction is processing, accept partial, orphan, extra, wrong-version, or wrong-attempt frame sets as AI evidence, infer completion from the source video alone, or require the same protected video to be uploaded again after a retryable extraction failure.",
      "Keep every client-extracted frame linked to its selected protected source video in the same workspace and context; describe that as user-submitted parent linkage, not cryptographic pixel proof.",
      "Do not send existing private grow media to diagnosis or IPM until the user explicitly selects each photo and its grow/plant/log provenance is preserved.",
      "Do not silently select an active grow for grow-optional Diagnosis or carry an old AI-proposed crop identity into a saved-evidence retry.",
      "Do not drop attached photo evidence or prior crop-identity provenance during follow-up analysis, treat a supplied crop name as explicit confirmation, or coerce blank measurements to zero.",
      "Do not present a photo result without the shared evidence review summary; preserve pixel-analysis status, quality, confidence, counter-evidence, missing checks, and a clear re-run path.",
      "Facility follow-up tasks created from shared tools must use the selected Facility task scope and credits, never fall back to the member's Personal task or balance.",
      "A structured GPT IPM second opinion does not independently inspect photo or video pixels.",
      "Do not label a combined billable scout-and-GPT action as a free calculator or hide its AI-credit cost until after the run.",
      "Do not count empty AI-prefill keys as filled fields or display raw empty arrays as scout evidence.",
      "Do not overwrite explicit user-entered scout fields with AI prefill or discard the image-analysis provenance when the user reviews an AI draft.",
      "Do not count an edit to an AI-prefilled value as a second independent user-observation channel.",
      "Do not derive scout or trap counts from photos, and do not count unknown placeholder phrases as completed IPM fields.",
      "Do not treat one photo copied into several fields as independent evidence, treat an AI hypothesis as a directly observed organism, or headline powdery mildew from generic white marks alone.",
      "Do not convert characters named inside unclear-whether, could-be, possible, comparison, or differential clauses into direct organism, disease-sign, damage-pattern, or supporting evidence.",
      "Do not convert negated findings, instructions, questions, failed media analysis, or unattested client-supplied visual text into supporting evidence, completed inspection fields, candidate scores, image gates, confidence, severity, or treatment categories.",
      "Do not use a separate or unbound list of media view roles to satisfy a candidate evidence gate.",
      "Do not let morphology for one candidate raise the confidence or direct-treatment status of a different leading candidate.",
      "Do not report IPM severity from diagnostic confidence when plants affected, distribution, and progression are missing.",
      "Do not answer a result follow-up from an untrusted client snapshot, overwrite the original result, show a cannabis-specific shortcut without cannabis context, or infer plant sex from stems, stipules, or undeveloped nodes.",
      "Do not offer secure follow-up for a legacy or unattested saved IPM result, or let follow-up prose exceed the saved confidence and severity ceilings.",
      "Do not strand a newly selected diagnosis or IPM upload as non-AI-usable after explicitly disclosing and receiving current-workflow AI approval.",
      "Do not leave a failed or timed-out media transfer in an indefinite uploading state, upscale an oversized photo, claim preparation restored detail, or duplicate a completed binary upload when only evidence registration needs retrying.",
      "Do not publish a protected diagnostic original, charge it to the wrong workspace, or create a public Nature derivative without explicit publication consent.",
      "Do not invent scout defaults, trap context, organism identity, pesticide products, or rates.",
      "Do not require a grow for crop identification or infer a cultivar from cannabis flower appearance.",
      "Do not overwrite explicit crop-identification context or infer exact location, date or season, sensory observations, measurements, or wild-versus-cultivated status from images.",
      "Do not auto-populate or auto-upgrade a crop or species identity from limited or unusable lighting evidence; preserve directly visible morphology only, retain at most a low-confidence crop, family, or genus candidate when limited evidence remains readable, require a retake when the needed characters are hidden, and keep user-entered names labeled as user claims.",
      "Do not reject nighttime, a dark background, phone-light illumination, or direct flash by label alone; reject only when the captured detail needed for the proposed identity is actually obscured or unreliable.",
      "Do not retain a low-light Cannabis or other taxon guess from a generic serrated leaf, stem, or growth habit alone; request targeted retakes unless the candidate's own evidence contains a discriminating combination.",
      "Do not count a bare structure name, an unavailable or negated character, or an inconclusive lookalike comparison as affirmative diagnostic evidence.",
      "Do not allow one broadly shared character to retain an exact species for any taxon, or allow high/confirmable species without recorded authoritative-source support.",
      "Do not select an alternate candidate genus when the primary identity is different or the available genera remain ambiguous.",
      "Do not let inferred cultivar, strain, variety, or trade labels survive through common-name or display-name fields; preserve only explicit user-entry provenance.",
      "Do not let a repeated review of unchanged crop-identification evidence silently replace the earlier draft or turn a prior limitation into user-entered evidence; expose the disagreement and require changed evidence or explicit human review.",
      "Do not truncate the crop-identification provider request before its output schema, final safety rules, or bounded user context.",
      "Do not attribute device coordinates to AI prefill; capture them through a separate user-authorized action and keep them private by default.",
      "Do not replace a defensible broader crop candidate with a confirmation placeholder merely because exact species remains unresolved.",
      "Do not store a plain-language common-name phrase as a scientific name or possible species.",
      "Do not preserve medium or high identity confidence after a scientific-name conflict has been detected.",
      "Do not discard server-attested crop-identification vision provenance and relabel an analyzed result as text-only or unanalyzed.",
      "Do not accept a latest matching AI event in place of the exact receipt shown to the user, or let a generic saved-run update replace Plant ID evidence, AI output, receipt, or immutable snapshot.",
      "Do not infer legacy non-Facility evidence into Commercial scope, or recover a Saved Run by searching only a recent-evidence list instead of its exact workspace-scoped evidence IDs.",
      "Do not announce that saved Plant ID evidence was recovered or submit it for analysis when any exact asset is missing, not durably uploaded, outside Crop Identification, an unsupported type, or a photo that is not explicitly AI-usable; load none of an ineligible set.",
      "Do not mix Facility Plant ID credits, runs, evidence, logs, or tasks into the member's Personal workspace, and recheck current Facility membership on every read or write.",
      "Do not treat a route Commercial account ID as authorization, fall a Commercial Plant ID back to Personal Saved Runs, or create Personal logs or tasks from a Commercial run.",
      "Collect identification photos before the AI action and reserve user confirmation for the explicit result action.",
      "Recognizing cannabis from deliberately submitted crop-identification evidence must not unlock or advertise unrelated cannabis-only workflows.",
      "Public viewing never grants edit access; only Field Study owners and invited editors may change observations.",
      "Do not publish an observation, coordinates, or media by default, and do not expose private or collaborator-only coordinates through public APIs.",
      "Linking a saved Crop Identification result must not request location, publish an observation, change study visibility, confirm cannabis/hemp public context, or duplicate an existing observation for the same ToolRun and study.",
      "Do not let a standalone private Plant ID location action mutate a linked Field Study observation; require a separate audience-aware Field Study action to copy it as exact private data into that same observation.",
      "Do not create a public Nature observation from direct Plant ID location capture alone; require a separate approximate-pin choice and final publish action, and use the backend-required dedicated collection only as a hidden grouping rather than a new setup burden.",
      "Do not replace an observation's unspecified nested identity, evidence, coordinate, publication, sensitivity, cannabis-context, or public-note fields when updating one review or sharing setting.",
      "Do not mark an observation map-ready until an editable Field Study is public, evidence is attached, the observation is explicitly published, location privacy is public approximate or confirmed public exact, and coordinates are captured.",
      "Do not expose an exact public location without explicit observation-level confirmation; reduce sensitive-species locations to a wider approximate region.",
      "Do not expose identity-only public pins; omit observations whose owned photo cannot produce a safe public derivative.",
      "Do not call a plant invasive without a jurisdiction and authoritative source record.",
      "Do not deliver cannabis or hemp pins without deliberate observation publication, separately confirmed public cannabis/hemp context, and matching viewer grow-interest or content controls.",
      "Do not filter a public viewport against protected exact coordinates; query only the stored privacy-safe public point.",
      "Do not use a visitor's location for anything beyond centering their local view, and never publish it."
    ],
    ["plant-diagnosis", "ipm-scout", "species-crop-id", "field-studies", "ask-ai"]
  ),
  method(
    "pheno-hunting",
    "Pheno Hunting",
    ["genetics", "selection"],
    "pheno-hunting-method.md",
    ["early growth", "flower", "final product", "clone/TC", "decision"],
    ["plant history", "stress", "sensory", "yield", "propagation"],
    ["category decisions", "reasoning", "retest plan"],
    ["A composite score cannot replace final-product and role-specific decisions."],
    ["pheno-hunt", "pheno-matrix", "genetics-inventory"]
  ),
  method(
    "stress-testing",
    "Stress Testing and Recovery",
    ["stress", "selection"],
    "stress-testing-method.md",
    ["incident", "response", "recovery", "lasting impact"],
    ["stress history", "before/after evidence", "timing"],
    ["recovery record", "keeper impact", "tasks"],
    ["Do not invent resilience scores."],
    ["stress-test", "pheno-hunt"]
  ),
  method(
    "crop-steering",
    "Crop Steering",
    ["irrigation", "environment"],
    "crop-steering-method.md",
    ["intent", "measured pressure", "response", "stop/continue"],
    ["medium", "dryback", "EC/pH", "DLI/VPD", "response"],
    ["optional techniques", "prerequisites", "stop conditions"],
    ["Do not escalate pressure with missing data or unresolved stress."],
    ["crop-steering-project", "crop-steering-entry", "ph-ec-check"]
  ),
  method(
    "soil-nutrients",
    "Soil and Nutrients",
    ["soil", "water", "nutrients"],
    "soil-and-nutrient-method.md",
    [
      "open the unified mix-builder chooser",
      "select exactly one soil or nutrient builder",
      "verified inputs",
      "chemistry or structure",
      "release",
      "application"
    ],
    [
      "mix goal",
      "verified labels",
      "batch and water context",
      "stage",
      "lab or measured evidence when available",
      "history"
    ],
    [
      "label/elemental math or soil structure plan",
      "release timeline",
      "source confidence and uncertainty",
      "antagonisms",
      "owner-scoped recipe comparison and revision history",
      "zero-stock not-for-sale storefront draft handoff",
      "planned Facility production snapshot without inventory mutation",
      "commercial batch yield, packaging, cost completeness and inventory review",
      "tasks"
    ],
    [
      "Compost, biology, mineralization and long-term availability remain uncertain without testing.",
      "Official labels support guaranteed analysis and use rates, not superiority, uptake or crop response.",
      "Do not coerce missing batch quantity, analysis, cost, shrinkage, margin, lot or inventory values to zero.",
      "Calculate blended label analysis only from complete values expressed in compatible quantity units; inventory review never decrements stock.",
      "Never trust client-supplied storefront or Facility scope: storefront drafts require owner scope and Facility production batches require owner or manager access.",
      "Recipe handoff never publishes a product, enables checkout, claims inventory, or decrements stock."
    ],
    [
      "npk",
      "soil-builder",
      "ingredient-library",
      "nutrient-chemistry",
      "nutrient-source-comparison",
      "dry-amendment-mix",
      "topdress-plan",
      "ph-ec-check",
      "watering",
      "feeding-schedule"
    ]
  ),
  method(
    "clone-rooting",
    "Clone Rooting",
    ["propagation"],
    "clone-rooting-method.md",
    [
      "select owned cannabis/hemp grow",
      "count batch",
      "record direct root evidence",
      "record measured context",
      "review bottlenecks and missing evidence",
      "schedule recount",
      "record outcome"
    ],
    [
      "days since cut",
      "total/rooted/failed counts",
      "direct root evidence",
      "optional callus/wilt counts",
      "timestamp and measurement source",
      "humidity, air/root-zone temperature, PPFD and photoperiod when measured",
      "mother health, sanitation, medium, stem and leaf observations",
      "photo analysis provenance"
    ],
    [
      "evidence status",
      "validated batch counts and percentages",
      "measured environment snapshot",
      "structured bottlenecks and counter-limits",
      "missing information",
      "source and method IDs",
      "recount/photo/environment/outcome tasks"
    ],
    [
      "Require an owned cannabis/hemp grow at the API boundary.",
      "Do not use elapsed days, top growth, callus, or tug resistance as proof of hidden roots.",
      "Do not silently default counts, environmental measurements, donor health, sanitation, or media observations.",
      "Present published environmental ranges as cultivar- and study-specific context, never universal targets.",
      "Attached media is not analyzed unless provider execution evidence confirms pixel inspection."
    ],
    ["clone-rooting"]
  ),
  method(
    "tissue-culture",
    "Tissue Culture",
    ["lab", "propagation", "genetics"],
    "tissue-culture-method.md",
    [
      "select owned cannabis/hemp grow",
      "identify batch, workflow lane and stage",
      "record timestamped direct vessel counts",
      "link lineage, SOP, media, sterilization and custody",
      "review visible patterns without naming microorganisms",
      "review quality controls and release blockers",
      "compare protocol, acclimation, storage and recovery outcomes",
      "schedule owner-timed follow-up"
    ],
    [
      "project and batch identifiers",
      "mother-bank, production, cold-storage or cryopreservation lane",
      "stage and direct-inspection status",
      "timestamp, observation source and total/condition vessel counts",
      "lineage, vessel/rack/shelf, SOP/media/sterilization lots and custody",
      "quality-control reports and disposition",
      "measured environment, protocol cohort, acclimation, cost and storage evidence",
      "photo analysis provenance"
    ],
    [
      "assessment, lane and stage",
      "validated counts and percentages",
      "structured visible failure modes and limits",
      "traceability and release blockers",
      "quality, protocol, acclimation, cost, storage and recovery records",
      "source and method IDs",
      "evidence and owner-timed tasks"
    ],
    [
      "Require an owned cannabis/hemp grow at the API boundary.",
      "Do not silently default counts, identifiers, lots, measurements, costs or transfer timing.",
      "Visible patterns and photos cannot identify microorganisms, prove pathogen freedom or replace laboratory evidence.",
      "Do not automatically release material; surface blockers for owner review.",
      "Keep ordinary cold storage separate from validated cryopreservation.",
      "Published protocol values are study- and genotype-specific context, not universal targets."
    ],
    ["tissue-culture"]
  ),
  method(
    "run-comparison",
    "Run Comparison and Grow History",
    ["run comparison", "grow history", "analytics"],
    "run-comparison-method.md",
    [
      "select two to five owned grows",
      "choose reference, objective and equivalent scope",
      "inventory saved evidence",
      "compare recorded values",
      "separate differences from associated drivers",
      "review missing data and alternatives",
      "save report and optional next-run tasks"
    ],
    [
      "owned grow IDs",
      "reference grow",
      "comparison objective",
      "equivalent stage or whole-run scope",
      "saved logs, tasks, ToolRuns, diagnoses, telemetry and outcomes"
    ],
    [
      "evidence inventory by grow",
      "normalized snapshots",
      "recorded differences",
      "associated-driver hypotheses with alternatives",
      "missing information",
      "confidence and limitations",
      "method and source IDs",
      "owner-reviewed follow-up tasks"
    ],
    [
      "Do not use demo runs or silently convert missing values to zero.",
      "Do not rank an overall best run with hidden weights.",
      "Do not compare unlike stages without an explicit limitation.",
      "Do not claim causation from an observational run comparison.",
      "Exclude synthetic QA evidence from ordinary production conclusions unless it is explicitly selected and labeled.",
      "The deterministic comparison uses no AI credit; optional AI explanation must preserve the same evidence limits."
    ],
    ["run-comparison"]
  ),
  method(
    "harvest-dry-cure",
    "Harvest, Dry and Cure",
    ["harvest", "post-harvest"],
    "harvest-dry-cure-method.md",
    [
      "readiness evidence",
      "decision",
      "measured dry/cure",
      "outcome",
      "photo-review provenance and AI-credit outcome"
    ],
    [
      "three macro bud-site photos plus one wider context photo",
      "up to 12 role-diverse photos when additional representative bud sites are needed",
      "one optional private source video up to 9 minutes 59 seconds with up to 12 timestamped candidate still frames spanning the timeline",
      "maturity",
      "telemetry",
      "sensory",
      "simultaneous measured room temperature and RH",
      "optional coldest material or container surface temperature",
      "equilibrated jar or bag RH",
      "measurement time and source",
      "days in the current stage",
      "explicit light exposure condition",
      "airflow and material density"
    ],
    [
      "window",
      "missing media",
      "risk",
      "tasks",
      "air dew point and explicitly labeled air spread",
      "surface-to-dew-point margin only when a surface temperature was measured",
      "evidence used, missing information, and limitations",
      "stage timing that distinguishes a 24-hour recheck from completion",
      "10-14 day controlled-dry planning context and 5-7 day fast-dry quality warning",
      "review ID, evidence IDs, provider/model and image detail, set-level quality checks, per-image findings, visible traits, limitations, photo count, and credit status",
      "server-attested harvest image receipt bound to the authenticated workspace, optional canonical grow, optional plant, exact evidence set, normalized result digest, evidence fingerprint, and review-policy version",
      "exact selected Harvest media set separated from the analyzed still/frame set, with a private source video retained as non-AI provenance",
      "authenticated cannabis-enabled Personal, Commercial, or Facility workspace scope with an optional authorized grow, plus Facility write-role and Facility-credit enforcement",
      "additive reviewable trichome-percentage drafts that preserve manual maturity observations and retain visual provenance",
      "user-reviewed trichome values saved as a manual override while the exact attested photo result remains separately visible",
      "original-resolution images plus source-bound enlarged diagnostic crops that never count as independent evidence",
      "staging-only same-pixel trichome luminance audit with the original mean, bounded uniform RGB multiplier, and method retained as non-independent evidence that cannot confirm amber by itself",
      "bounded amber visibility and exact image-region basis even when a complete trichome distribution remains unavailable",
      "bounded cloudiness observation with confidence and matched-frame basis, distinguishing directly resolved cloudiness, persistent likely cloudiness, glare-obscured whiteness, and uncertainty",
      "exact dedicated Harvest vision model recorded in the signed review without inheriting a cost-optimized global mini model",
      "overlapping full-area macro coverage for every original in the minimum four-photo Harvest set, reaching the left, right, top, and bottom image bounds while deduplicating overlap by position",
      "versioned signed Harvest sampling policy that separates retired centered-crop reviews from full-area-grid reviews in saved results and calibration evidence",
      "client preflight that accepts ordinary 1080p phone photos without claiming trichome heads are unresolved from dimensions alone, leaving subject scale, focus, compression, glare, lighting, calyx placement, and head detail to server review",
      "saved-evidence hydration that retires the replaced Harvest dimension-only warning while preserving current focus, glare, compression, lighting, and provenance findings",
      "bounded staging-counter tile selection that preserves spatial coverage of each large source photo before filling remaining detector slots by sharpness without treating tiles as independent sites",
      "staging qualitative clear, cloudy, and amber seed cases spanning at least two independent rights-reviewed primary sources, with reviewed tight crops and cryptographic source pins where packaged supplements are used, retained as sanity evidence rather than quantitative counter calibration",
      "visible sampled-head evidence split into clear, cloudy, directly confirmed amber, amber-or-warm-light, and cloudy-or-glare with exact region basis, a strict confirmed floor separated from the possible amber total, and an explicit no-whole-plant-percentage boundary",
      "server-calculated visible-sample percentage from non-overlapping per-original resolved-head tallies, including counted-head total and low, medium, or high counting confidence",
      "immediate and saved per-photo inspected-area breakdown with five-bucket counts, percentages, amber range, exact region, resolved-head total, counting confidence, and a strongest-amber-area callout that retains the no-whole-plant boundary",
      "no-credit user correction bound to the exact signed review and policy version, preserving the AI amber range, the owner's photographed-area estimate, optional basis, and separate off-by-default calibration consent",
      "versioned Harvest calibration authorization that separately confirms image rights, limits use to private internal AI evaluation and calibration, and does not authorize public display",
      "counting confidence capped by both resolved-head volume and weighted per-photo counting confidence, with not-counted, duplicate-image, blurred, blocking-glare, and unresolved-detail findings excluded from resolved-head tallies",
      "calculator and saved-run retention of the attested visible-sample five buckets, counted-head total, count source, confidence, exact basis, directly confirmed amber floor separated from the possible amber total, cloudy-versus-glare uncertainty, and inspected-area-only boundary even when representative autofill remains blank",
      "one-click Personal saved-run retry that restores the exact retained Harvest evidence with optional canonical grow context without spending a credit until the user starts analysis",
      "explicit Personal owned-harvest-batch selection scoped to the current grow, cleared on grow changes, and used only for user-triggered review write-back",
      "explicit user-date or breeder-timing planning range with separate reasons the window may be open, reasons to wait, missing evidence, confidence, and a non-trichome-date boundary",
      "Harvest Readiness named and explained as a multi-signal review, with trichome photo review presented only as one evidence component"
    ],
    [
      "Never estimate sensor values from images.",
      "Never default missing dry/cure temperature, RH, airflow, or density to a plausible-looking value; incomplete measurements produce an insufficient-evidence result.",
      "Never call air temperature minus dew point a surface condensation margin. Calculate a surface margin only from an entered coldest-surface measurement.",
      "Never label mold risk as low or ruled out from one room reading, a photo, or the absence of visible growth.",
      "Keep drying and curing material protected from light; record dark, brief work light, continuous indirect light, direct light, or unknown without guessing from a photo.",
      "Treat a 24-hour task as a recheck, never completion. Show 10-14 days only as a controlled-drying planning window, 5-7 days as a possible fast/hot/low-humidity quality concern, and longer than 14 days as possible but not recommended as routine; elapsed time alone never completes the stage.",
      "Require cannabis/hemp grow context at the Dry / Cure Guard API boundary before saving a ToolRun.",
      "Never fill trichome percentages after upload failure, unavailable analysis, incomplete provider output, or unusable media; show actionable retake guidance.",
      "Block provider use and spend no AI credit until three sharp macro bud-site samples plus one wider context photo are uploaded and approved for this workflow.",
      "Reject obviously tiny or invalid files before upload, but use actionable retake guidance rather than pretending metadata alone can detect blur, glare, lighting, or missing sample roles.",
      "Use provider original-detail image review by default when the dedicated Harvest model supports it, with high detail only as an incompatible-model or explicit operational fallback; never claim digital zoom restored pixels hidden by blur, compression, or clipped glare, and report each image's usable regions or exclusion reason.",
      "Use a dedicated configurable full-size Harvest vision model and keep every server-side evidence safeguard; a stronger model never makes unresolved pixels, missing role coverage, or incomplete distributions usable.",
      "Preserve an optional source video shorter than 10 minutes as non-AI evidence and analyze only up to 12 timestamped candidate still frames spanning its timeline. Each frame counts toward the 12-photo ceiling and must pass the same macro, role, focus, lighting, and glare checks. When the same head or tightly matching region stays diffusely white across adjacent frames while focus, angle, or highlight position changes, retain lower-confidence likely cloudiness with its matched-frame basis; treat blooming, clipped, glowing, flashing, or moving whiteness as glare-obscured. Never count that bounded likely observation alone as a complete distribution or chemical measurement.",
      "Reserve one disclosed AI credit only after evidence ownership is verified, refund provider failures, and preserve the charge/refund result in the review.",
      "Reject crop-neutral accounts and unrelated horticulture grows before loading harvest evidence or reserving an AI credit.",
      "Allow a cannabis-enabled Personal, Commercial, or authorized Facility workspace to run Harvest Readiness without creating or attaching a grow; bind standalone evidence and the receipt to that authenticated workspace, keep canonicalGrowId null, retain Facility-credit ownership, and disable only grow-linked history, task, and batch actions.",
      "Never trust client-supplied harvest provider metadata, AI percentages, evidence IDs, or an analysis ID as proof of image analysis; validate the exact server receipt and reconstruct the saved photo result.",
      "Never omit an attached private source video from the selected receipt set, count it as visually analyzed, accept only a subset of its active client-generated Harvest frames, or accept a generated frame without the selected protected source and matching workspace, grow, plant, and purpose lineage.",
      "Never treat results produced by different Harvest sampling-policy versions as repeatability evidence from one method, rewrite the signed estimate with a user correction, or infer permission for model calibration from product feedback.",
      "Never admit a Harvest correction or its exact evidence to calibration from an older boolean alone; require the current versioned consent, an explicit image-rights affirmation, private internal-use scope, and no public-display grant.",
      "Never trust a route account or grow ID as shared-workspace authority, spend individual credits for a Facility Harvest run, or allow a Facility viewer to run the analysis.",
      "Never remount Harvest Readiness or overwrite manual maturity fields when applying AI trichome percentages; invalidate only unreviewed visual drafts when their evidence changes.",
      "Never overwrite a user-reviewed trichome percentage with the attested AI value or continue labeling an edited distribution AI-derived; preserve it as a manual override, reconstruct each unreviewed field from the attested snapshot, clear unusable unreviewed drafts, and retain the attested photo snapshot separately.",
      "Never silently coerce missing trichome observations to zero or score a distribution that does not total about 100%.",
      "Never replace or downscale the original image for AI inspection; diagnostic crops supplement the original and remain bound to it rather than counting as another photo, sample, site, or observation.",
      "Never count bright pixels, sparkles, pistils, plant hairs, colored plant tissue, blurred circles, compression artifacts, sugar-leaf edge heads, or the same head repeated in overlapping crops as resolved trichome heads; ambiguous resolved white heads belong in cloudy-or-glare, while resolved yellow/orange/tan/brown heads that cannot be separated from warm light belong in amber-or-warm-light and define only the possible-amber upper bound. Under mixed or warm light, audit every clear head against adjacent highlights, transparent heads, and transmitted background so colored uncertainty cannot remain clear merely because the entire image is warm.",
      "Never convert missing qualified trichome evidence into a generic three-to-seven-day harvest recommendation or imply trichome maturity was assessed. A low-confidence planning range is allowed only from an explicit user approximate date or explicit flower-day plus breeder timing, with separate reasons to harvest, reasons to wait, missing evidence, and range provenance; it cannot create an automatic harvest decision or dry/cure deadline.",
      "Never let fresh pistils alone overrule a qualified representative advanced-amber distribution; surface the open harvest window and explain uneven or newly developing tissue as a possible conflict to review.",
      "Never accept a free-text harvest-batch database ID, let AI select a batch, or retain a batch selection after grow context changes; an estimate remains valid without batch write-back.",
      "Keep the shared harvest-readiness route discoverable in cannabis-aware Personal Tools and contextual cannabis grow surfaces, including untagged legacy cannabis grows and grows with attached cannabis-only workflow evidence."
    ],
    ["harvest-readiness", "dry-cure-guard"]
  ),
  method(
    "video-sharing-workflow",
    "Video Sharing Workflow",
    ["video", "discovery", "following", "media"],
    "video-sharing-workflow-method.md",
    [
      "upload or link",
      "reserve and verify private storage",
      "review rights and accessibility",
      "save once",
      "publish with visibility",
      "discover or follow",
      "reuse by reference"
    ],
    [
      "active Personal, Commercial, or Facility workspace",
      "video source",
      "title and description",
      "creator rights confirmation",
      "availability and accessibility review",
      "explicit visibility",
      "cannabis/hemp classification",
      "authoritative storage size for GrowPath uploads"
    ],
    [
      "workspace-owned reusable video record",
      "truthful workspace storage usage and limit",
      "verified private object and authorized short-lived playback",
      "public or follower-scoped Discover result",
      "creator follow action from video detail",
      "stable course and content references",
      "reference-safe detach and deletion status",
      "cannabis-aware discovery filtering",
      "stored video moderation case with exact-content and administrator-email links"
    ],
    [
      "Never limit video upload or sharing only to accounts labeled as creators.",
      "Never let Facility Staff remove another member's draft or any published Facility video.",
      "Never expose private, unlisted, course-only, or Facility-internal videos in public Discover.",
      "Never treat a client-provided flag as proof that the viewer follows a video owner.",
      "Never duplicate an upload merely to attach one reusable video to a course.",
      "Never delete a library video while a course or supported record still references it.",
      "Never claim storage was released until the storage service confirms physical deletion.",
      "Never persist object-storage credentials or expiring signed upload or playback URLs in video, course, or lesson records.",
      "Never show cannabis/hemp-specific video discovery to unrelated horticulture viewers.",
      "Never treat video popularity, follows, or engagement as scientific verification or AI-training permission.",
      "Never send a video-report email before storing the report and moderation case, accept an off-site reported-content link, or erase the report when email delivery fails."
    ],
    ["videos", "discover", "course-builder", "profiles", "following-feed"]
  ),
  method(
    "course-media-workflow",
    "Course Media Workflow",
    ["course", "lesson", "education", "media", "payment", "refund"],
    "course-media-workflow-method.md",
    [
      "choose source",
      "normalize provider",
      "review rights and availability",
      "record accessibility fallback",
      "publish",
      "privacy-aware playback"
    ],
    [
      "GrowPath upload or video-page URL",
      "creator rights confirmation",
      "timestamped availability check",
      "captions or transcript status",
      "learner-visible text summary",
      "signature-verified paid checkout webhook",
      "active learner enrollment",
      "recorded refund or payment-support state"
    ],
    [
      "normalized provider metadata",
      "canonical URL and provider ID",
      "Vimeo unlisted privacy hash when present",
      "approved embed capability or link-only fallback",
      "learner-visible availability and accessibility status",
      "external provider link",
      "authorized short-lived playback for protected GrowPath library videos",
      "GrowPath-only explicit completion state",
      "owner-only draft preview and published-only public detail access",
      "learner preview without authoring controls",
      "signed-out published catalog without owned-course or authoring controls",
      "one provider-aware media contract shared by initial course creation and later lesson editing",
      "shared Full Course Builder creation routed into the active workspace's canonical course collection, including Commercial draft persistence in Commercial Courses",
      "flat canonical Commercial course grow-interest tags with separately retained structured builder selections and legacy-reader normalization",
      "outer bounded-total independent public, owned, and Commercial-public catalog loading, including token retrieval, with partial results and a named retry action",
      "stable authenticated identity dependencies that cannot restart catalog loading on each result render",
      "owner-controlled publish and private-draft unpublish",
      "confirmed owner-scoped soft archive for unpublished generic course drafts with retained audit history",
      "single page heading, ordered level-two builder steps, one shared back action, and checked pricing or access controls",
      "paid discovery metadata without protected lesson, assessment, document, or media content",
      "webhook-confirmed paid enrollment and idempotent course counters",
      "buyer-visible payment, refund, and GrowPath support status",
      "refund-adjusted and dispute-held creator earning",
      "creator payout eligibility limited to available unpaid earnings",
      "stored course moderation case with exact-content and administrator-email links"
    ],
    [
      "Never accept or execute author-supplied iframe, script, object, embed, video, or HTML markup.",
      "Never imply GrowPath owns, hosts, continuously monitors, or verifies watch analytics for third-party media.",
      "Never publish video without rights confirmation, a timestamped availability check, accessibility status, text summary, and external-link fallback.",
      "Never drop a Vimeo unlisted privacy hash while normalizing its canonical or player URL.",
      "Never persist object-storage credentials or expiring signed playback URLs in a course or lesson.",
      "Never expose unpublished course or lesson content to anonymous users or unrelated accounts, including through a direct record ID.",
      "Never request owned courses or expose authoring, invite, analytics, publish, unpublish, enrollment, purchase, or progress controls before authentication.",
      "Never expose submit, approve, or reject course actions unless a real moderated-review backend workflow and role policy are implemented end to end.",
      "Never hard-delete a generic course through routine cleanup or archive a published course without returning it to a private draft first.",
      "Never expose duplicate course-authoring back actions, multiple page-level headings, unchecked pricing or access choices, or raw stored values as course labels.",
      "Never create a Commercial Full Course Builder draft through a separate generic course path that disappears from Commercial Courses or bypasses the Commercial lesson, publish, unpublish, and archive lifecycle.",
      "Never render a structured grow-interest selection as object text or assume every persisted Commercial course grow-interest value is already an array.",
      "Never let one unavailable course source leave the shared catalog loading forever or hide courses returned by the other sources.",
      "Never depend on a referentially unstable whole user object for the course catalog load effect.",
      "Never expose paid lesson text, media, documents, assessments, protected playback, or completion controls before active enrollment.",
      "Never treat checkout creation, a success redirect, direct enrollment, or lesson completion as proof of paid access.",
      "Never increment paid enrollment, revenue, or creator earnings more than once when Stripe retries a webhook.",
      "Never show refund or payment-issue forms without a recorded paid purchase, or label GrowPath support intake as a bank, card-network, or Stripe dispute.",
      "Never include held or refunded course earnings in creator payout eligibility.",
      "Never send a course-report email before storing the report and moderation case, accept an off-site reported-content link, or erase the report when email delivery fails.",
      "Provider playback never completes a GrowPath lesson automatically."
    ],
    [
      "course-builder",
      "course-player",
      "commercial-courses",
      "facility-training",
      "course-payments"
    ]
  ),
  method(
    "commercial-workflow",
    "Commercial Workflow",
    ["commercial"],
    "commercial-workflow-method.md",
    ["formula", "batch", "trial", "outcome", "product"],
    ["commercial records", "verified claims"],
    [
      "linked workflow",
      "limitations",
      "tasks",
      "single-heading campaign authoring with named stateful controls",
      "campaign draft review that distinguishes planned publish status from current state and uses user-facing filters",
      "inactive Commercial tab screens detached from web layout and focus order",
      "compact Commercial navigation with the active secondary workspace and a complete More destination",
      "compact shared-page content and campaign rails retained in non-overlapping document flow",
      "one level-one Product Lines heading with level-two workflow sections and level-three saved-line headings",
      "single-flight Product Line creation and detail editing with retained failed drafts and in-page status",
      "one level-one Soil & Nutrient Batch Planner heading with level-two workflow sections and level-three saved-batch headings",
      "one level-one Product Trials heading with level-two workflow sections and level-three saved-trial headings",
      "one level-one Product Trial Evidence Runs heading with distinct level-two workflow sections and level-three saved-run headings",
      "one level-one Commercial Inventory Support heading with level-two workflow sections and level-three saved-record headings",
      "capability-gated Commercial inventory creation exposed as a named actionable control",
      "readable owner-scoped Product Trial record pickers with an explicit advanced ID fallback",
      "single-flight Product Trial creation with positive whole-number plant counts and retained failed drafts",
      "authenticated purchase-intent concept trials with owner-approved artwork, positive hypothetical price, explicit not-for-sale disclosure, one revisable response per account, and aggregate-only owner results",
      "mutually exclusive single-flight Product Trial detail, claim-review, and evidence-task writes",
      "readable owner-scoped Product Batch record pickers with an explicit advanced ID fallback",
      "single-flight Product Batch creation and AI prefill with non-negative numeric validation and owner-value preservation",
      "mutually exclusive single-flight Product Batch detail and production-task writes with unknown-safe cost handling",
      "readable owner-scoped Product Trial Evidence Run record pickers and named share status choices with an explicit advanced ID fallback",
      "single-flight Product Trial Evidence Run loading, creation, and detail editing with positive whole-number plant counts and retained drafts",
      "named Inventory Support item types and readable Product or Evidence Run pickers with an explicit advanced fallback",
      "single-flight Commercial Inventory Support creation with non-negative stock validation and retained failed drafts",
      "single-flight Commercial Inventory Support loading and detail editing with non-negative stock validation and retained drafts",
      "forum alerts",
      "accessible inline Forum reply expansion and text reply composition on canonical post previews",
      "canonical Forum Directory group discovery and accessible group creation",
      "moderation audit",
      "server-enforced audited Forum moderation with feed-projection removal, reversible soft removal, and locked-reply blocking",
      "stored reports for Forum, Feed, storefront, course, video, and live content with focused administrator-email links",
      "owner-scoped event analytics",
      "one level-one Commercial Analytics heading with level-two metrics, breakdown, and guidance sections",
      "bounded Personal home campaign density that preserves the grow workspace",
      "owner-scoped production batches linked to ToolRuns and Commercial tasks",
      "published-course discovery limited to published storefronts and explicit public fields",
      "public Commercial projections exclude testing, test-only, QA-only, synthetic, and QA-seed records while preserving owner-scoped review",
      "slug-gated public storefront preview actions with truthful setup guidance",
      "single-flight Commercial storefront loading and mutually exclusive storefront, product, media, and setup-task actions with retained drafts",
      "single-flight Commercial order and analytics requests with retained last-good data, explicit cancellation confirmation, and truthful failure-versus-zero states",
      "explicit dispensary discovery by state or user-authorized distance with published linked inventory and external-site or in-store-pickup handoff",
      "signed-out course discovery limited to published learner-facing catalog fields",
      "signed-out Forum boundary with sign-in and registration actions instead of a protected-feed error",
      "direct draft-course detail limited to the authenticated author or platform administrator",
      "explicit eligible workspace preference preserved across plan-backed modes",
      "post-login workspace choice for every multi-workspace identity",
      "direct-entry and hard-reload support for workspace choice and switching",
      "workspace preference reapplied before restricted-route access decisions",
      "workspace selection and routing use the same effective paid-plan capabilities",
      "one 30-day trial per paid plan for Pro, Commercial, and Facility, with legacy trial use mapped to Pro and a second price-labeled confirmation before immediate Stripe billing",
      "visible Checkout success or cancellation feedback with an account refresh after success",
      "review-only SOP/checklist recommendations with starter version, rationale, missing information, and separately confirmed grow-task conversion",
      "clear not-configured guidance for unavailable third-party integrations",
      "connection-derived read-only EventSub status and checked Commercial Live visibility controls",
      "readable calendar selection with direct year, month, day, and optional time controls",
      "single-flight review-first CSV and PDF catalog import with cross-platform status feedback",
      "server-enforced Commercial course readiness with draft-only creation, save-before-publish, explicit unpublish, and published-content mutation lock",
      "confirmed owner-scoped soft archive for private Commercial course drafts with retained audit history"
    ],
    [
      "Never cross workspace scope or invent product claims.",
      "Never expose campaign types, placements, filters, or publish actions as generic unnamed controls.",
      "Never describe a blocked or unpublished campaign draft as currently active or expose raw campaign type values as filter labels.",
      "Never leave focusable controls from an inactive Commercial tab in the web keyboard order.",
      "Never let compact campaign rails shrink, cover, intercept, or displace Commercial workspace controls.",
      "Never expose a duplicate navigator title or a flat generic-text outline on Product Lines.",
      "Never clear a failed Product Line draft, submit a Product Line create or update twice, or depend on a native-only failure alert.",
      "Never expose a duplicate navigator title or a flat generic-text outline on the Soil & Nutrient Batch Planner.",
      "Never expose a duplicate navigator title or a flat generic-text outline on Product Trials.",
      "Never expose a duplicate navigator title or reuse one generic section label for different Product Trial Evidence Run jobs.",
      "Never expose a duplicate navigator title or a flat generic-text outline on Commercial Inventory Support.",
      "Never expose an authorized Commercial inventory write entry point as visually clickable generic text.",
      "Never require an ordinary Commercial user to find or paste database IDs to link a Product Trial.",
      "Never submit a Product Trial twice, accept a non-positive or fractional plant count, discard its failed draft, or depend on a native-only failure alert.",
      "Never let a purchase-intent concept trial create inventory, a reservation, an order, checkout, payment, shipping promise, production commitment, or public display of unapproved or rights-blocked artwork.",
      "Never allow duplicate or concurrent Product Trial detail, claim-review, or evidence-task writes, discard their failed drafts, or detach a task from the exact trial context.",
      "Never require copied database IDs as the primary way to connect a Product Batch to saved Commercial records.",
      "Never silently omit an invalid Product Batch volume or cost, submit a create or AI-prefill request twice, erase owner-entered values when AI leaves fields blank, or discard the failed draft.",
      "Never turn a blank Product Batch detail cost into zero, silently omit an invalid cost, allow duplicate or concurrent detail/task writes, or detach a production task from its batch context.",
      "Never require copied database IDs or raw public-share status codes as the primary Product Trial Evidence Run creation workflow.",
      "Never silently omit an invalid Product Trial Evidence Run plant count, submit a create or detail write twice, discard its failed draft, treat public-ready as automatic publication, or expose contextual AI before the exact record loads.",
      "Never make opaque record IDs or undocumented type values the default Commercial inventory setup workflow.",
      "Never silently coerce invalid Commercial inventory quantity or reorder values to zero, submit the same creation twice, discard the owner's failed draft, or depend on a native-only create-failure alert.",
      "Never silently omit an invalid Commercial Inventory Support detail quantity or reorder point, submit a detail write twice, overwrite its failed draft, or hide a load/save failure.",
      "Never require a page transition merely to read or write an ordinary Forum text reply from a canonical post preview.",
      "Never strand Forum group creation in a legacy compatibility screen or hide public-versus-private discoverability.",
      "Never leave hidden or soft-removed Forum content in shared feeds, accept replies on locked threads, hard-delete moderation evidence, or perform a moderator action without a case and platform audit event.",
      "Never count repeated Forum reports from the same account toward an automatic hold threshold.",
      "Never send a content-report email before storing the report and moderation case, accept an off-site reported-content link, or erase the report when email delivery fails.",
      "Never hide a Commercial workspace at compact widths without a visible replacement path from More.",
      "Never expose Commercial Analytics metric, breakdown, or guidance sections as additional level-one page headings.",
      "A batch calculation may report inventory shortages but cannot decrement stock, assign lots, publish claims or authorize release.",
      "Never expose drafts, owner/account IDs, arbitrary authoring fields, or private records through public commercial-course discovery.",
      "Never expose testing, test-only, QA-only, synthetic, or QA-seed Commercial records through public directories, feeds, details, related records, or checkout.",
      "Never route a public storefront preview through an invented or placeholder slug.",
      "Never silently omit invalid storefront coordinates, support email, HTTPS handoff, or product price, publish an incomplete quick product, submit a storefront/product write twice, or hide a load/action failure.",
      "Never present a failed Commercial Orders or Analytics request as real zero activity, discard the last good snapshot after refresh failure, submit overlapping fulfillment writes, or cancel an order without explicit confirmation.",
      "Never include dispensaries in default horticulture discovery or offer GrowPath checkout, payment, delivery, shipping, or reservation for a dispensary item.",
      "Never invent dispensary availability or imply pickup completion; use published linked inventory and a dispensary-provided website or pickup instructions.",
      "Never expose course authoring controls or request owned-course records for an anonymous visitor.",
      "Never call the protected Forum feed for a signed-out visitor, invent a public thread list, or present an authorization failure as an empty Forum.",
      "Never treat knowledge of a draft course ID as permission to read, enroll, check out, discuss, or review it.",
      "Never honor deterministic test identity headers as production authentication.",
      "Never silently replace an explicitly selected eligible workspace with the account's primary billing mode.",
      "Never repeat a trial for the same paid plan or consume another paid plan's trial when one plan's trial is used.",
      "Never open an immediately billed Stripe checkout on the first action after the selected plan's trial has been used.",
      "Never present a Commercial AI procedure draft as an approved Facility SOP, invent its setpoints, chemical rates, or legal requirements, or save it without separate confirmation.",
      "Never inject a Facility plan, rating scale, approved limit, deviation process, label, or Facility role into a Personal or Commercial procedure recommendation unless selected records explicitly provide it.",
      "Never pass reserved public route words or malformed record IDs into database ID queries.",
      "Never allow an author to type an integration into a connected state or expose Commercial Live visibility as unselected raw values.",
      "Never expose raw integration transport codes as workflow content or claim an integration is connected without verified configuration state.",
      "Never require an ordinary Commercial user to type an ISO date or date-time string.",
      "Never depend on a native-only alert for Commercial catalog import fallback, permit duplicate concurrent extraction or draft-creation requests, accept a PDF extraction without a protected source URL, or imply an imported draft is published.",
      "Never publish an incomplete or unsaved Commercial course, accept typed lifecycle state, mutate published course content in place, or silently coerce an invalid paid price to zero.",
      "Never hard-delete a Commercial course through routine cleanup or archive a published course without returning it to draft first."
    ],
    ["commercial-batch-planner", "soil-nutrient-batch", "products", "trials", "forum-qna"]
  ),
  method(
    "facility-workflow",
    "Facility Workflow",
    ["facility"],
    "facility-workflow-method.md",
    ["facility", "room/zone", "assignment", "SOP/task", "audit"],
    ["facility scope", "roles", "rooms", "telemetry"],
    [
      "scoped actions",
      "audit links",
      "forum tasks and alerts",
      "moderation audit",
      "Facility-scoped audited Forum moderation with feed-projection removal, reversible soft removal, and locked-reply blocking",
      "stored Facility report with focused administrator-email links that preserve content authorization",
      "read-only integration state",
      "reviewed device mapping",
      "record-backed facility analytics",
      "read-after-write Facility invitation session handoff",
      "Facility-subscription-backed member role capabilities",
      "selected-Facility AI balance, reservation, refund, and weekly usage ledger",
      "legacy missing-balance materialization from an effective owner Facility entitlement",
      "individual-versus-Facility workspace choice after sign-in",
      "direct-entry and hard-reload support for workspace choice and switching",
      "cross-platform confirmed Facility member removal with preserved history",
      "title-based public outreach destination selection with advanced reference fallback",
      "read-after-write reconciled facility task queues",
      "stable accessible Facility task queue links",
      "credential-autofill-safe AI and parental-control inputs",
      "record-backed report counts with explicit untracked compliance evidence",
      "export readiness separated by open, resolved, and cancelled deviation status",
      "human-readable audit summaries with full-record drill-in",
      "readable audit-detail evidence context before immutable raw payloads",
      "readable selected-Facility context without database identifiers",
      "record-backed non-submitting Facility AI readiness presets",
      "selected-Facility Plant/Crop Identification, Plant Diagnosis, IPM Scout, and Saved AI Runs with Facility-safe back navigation",
      "cannabis-specific Facility AI discovery gated by structured eligible Facility grow evidence",
      "explicit Facility grow crop-type setup and correction so authorized owners and managers can establish the structured context required by crop-specific tools",
      "owner-only single-flight Facility AI validation with readable request feedback",
      "notification-backed Facility alerts with supported source and task actions",
      "named Facility task assignments, rooms, and record summaries",
      "readable Facility inventory details with confirmed mistaken-record removal",
      "collision-resistant Facility deviation references with controlled write failures",
      "template-backed or owner-entered SOP checklists",
      "actionable SOP steps with a Facility Journal evidence path before status review",
      "owner-reviewed setpoint-free standard SOP starters",
      "Personal and Commercial AI reuse limited to review-only starter recommendations",
      "Facility-scoped SOP document attachments that supplement an executable checklist",
      "version-preserving SOP revisions and non-destructive retirement",
      "Facility-scoped SOP create, revise, and retire audit events with readable title and version context",
      "human-readable two-run SOP comparison selection",
      "direct comparison-result links to both named SOP runs and Facility follow-up tasks",
      "review-complete and mutation-locked SOP evidence runs",
      "readable SOP evidence summaries and step differences",
      "separate seed-readiness and post-seed QA evidence",
      "readable calendar selection with direct year, month, day, and optional time controls"
    ],
    [
      "A selected facility and authorization are required.",
      "Facility AI must use the selected authorized Facility subscription balance for display, reservation, refund, and usage history; never fall back to a member's individual balance.",
      "Only a missing legacy Facility balance with an effective active or trialing owner Facility entitlement may be materialized; existing canceled or delinquent Facility subscription state remains authoritative.",
      "A confirmed Facility invitation must refresh canonical membership and enter the selected Facility without replacing the human's primary account.",
      "Never replace an individual account with Facility membership or bypass the post-login choice when both workspaces are eligible.",
      "Never rely on native-only Alert callbacks for web member-removal confirmation or remove the last owner.",
      "Never leave hidden or soft-removed Facility Forum content in eligible feeds, accept replies on locked threads, hard-delete moderation evidence, or change Facility-only visibility during moderation.",
      "Never count repeated Facility Forum reports from the same account toward an automatic hold threshold.",
      "Never send a Facility report email before storing the report and moderation case, expose content outside its authorization boundary, or erase the report when email delivery fails.",
      "Local previews require explicit preview intent; bare routes preserve real authenticated Facility sessions.",
      "Never hide a confirmed Facility task write behind a cached or stale queue response.",
      "Never make Facility outreach operators type raw course, live-event, or Forum identifiers when readable public records are available.",
      "Never make Facility task operators work from raw database fields, user IDs, room IDs, or JSON records.",
      "Never expose raw Facility inventory envelopes or internal identifiers as the primary item detail, or leave authorized operators unable to remove a mistaken record.",
      "Never expose raw source-object IDs in Facility task queue summaries or route a task row anywhere except its selected task detail.",
      "Never invite saved account credentials into an AI prompt or parental-control PIN field.",
      "Never use an internal Facility identifier as the visible workspace name, operational context label, or downloaded evidence filename.",
      "Never ignore a selected Facility AI preset, auto-submit its request, fabricate missing inspection evidence, or claim legal compliance.",
      "Never send a shared Facility AI tool back to Personal Tools, charge a member's Personal balance, or save its result outside the selected Facility scope.",
      "Never expose cannabis-specific Facility AI shortcuts from a facility name, free-text note, or unconfirmed image candidate; require structured eligible Facility grow evidence.",
      "Never require structured Facility crop evidence for a crop-specific tool while omitting the authorized grow setup and correction controls needed to record that evidence.",
      "Never expose Facility AI validation payloads or training-feedback exports outside a capable owner role, allow duplicate concurrent submissions, or leave an active request without readable progress and outcome feedback.",
      "Never show assign, snooze, or AI controls for a notification-backed alert without a server-backed action and its exact source context.",
      "Never show a raw account identifier as the assignee on a Facility alert card.",
      "Never route a notification-backed task alert to a detail record that may have been deleted; open the current task collection instead.",
      "Never leave a zero-grow Facility room at a backend-facing dead end or silently attach a room-scoped grow setup to every Facility room.",
      "Never let selecting or editing an existing Facility room overwrite the separate New Room draft.",
      "Never convert unavailable Facility compliance evidence to a zero or expose raw JSON, entity IDs, or identifier arrays in primary audit lists and summaries.",
      "Never ask an operator to mark an SOP step done or skipped without a visible action and a direct path to record evidence.",
      "Never make a Facility operator interpret raw audit JSON before showing the readable action, summary, time, and available actor context.",
      "Never treat a resolved or cancelled Facility deviation as an open cleanup blocker.",
      "Never allow a Facility deviation reference collision or persistence error to terminate the shared API service.",
      "Never create an empty SOP run or require a user to type internal run IDs for comparison.",
      "Never strand an SOP comparison result without direct paths to both compared runs and Facility follow-up tasks.",
      "Never auto-install a standard SOP starter as Facility policy or present it as legal compliance, treatment direction, release criteria, or facility approval.",
      "Never let a Personal or Commercial SOP recommendation imply Facility approval, assignment, uploads, versioning, run evidence, retirement, or audit status.",
      "Never let the shared starter baseline inject a Facility plan, rating scale, approved limit, deviation process, label, or Facility role into a non-Facility recommendation.",
      "Never allow an uploaded SOP document to replace the executable checklist, cross Facility boundaries, or be attached without owner/manager review.",
      "Never overwrite or hard-delete the prior SOP version when a Facility procedure is revised or retired.",
      "Never hide SOP retirement from an authorized owner or manager, label it as deletion, or retire an SOP without naming it and confirming that new runs stop while historical evidence remains.",
      "Never create, revise, or retire a Facility SOP without appending a Facility-scoped lifecycle audit event that can be understood without raw identifiers.",
      "Never complete an SOP run with unreviewed steps, mutate completed evidence, or expose raw run JSON as the primary interface.",
      "Never require an ordinary Facility operator to type an ISO date or date-time string.",
      "Synthetic QA approval never authorizes production records, operational setpoints, publication, or external source rights."
    ],
    [
      "facility-rooms",
      "facility-grows",
      "facility-tasks",
      "facility-inventory",
      "forum-qna"
    ]
  )
];

export function getMethod(id: string) {
  return methodRegistry.find((entry) => entry.id === id);
}

export function methodsForTool(toolKey: string) {
  return methodRegistry.filter((entry) => entry.relatedTools.includes(toolKey));
}
